import type { Achievement } from '@/types/game';

const DEFINITIONS = [
  [
    'first-directive',
    'First Directive',
    'Complete your first mission.',
    'Complete 1 mission',
    'spark',
  ],
  ['ten-directives', 'Orders Understood', 'Complete ten missions.', 'Complete 10 missions', 'list'],
  [
    'fifty-directives',
    'Reliable Candidate',
    'Complete fifty missions.',
    'Complete 50 missions',
    'shield',
  ],
  [
    'hundred-directives',
    'Century Mark',
    'Complete one hundred missions.',
    'Complete 100 missions',
    'crown',
  ],
  [
    'five-hundred-directives',
    'Unyielding Record',
    'Complete five hundred missions.',
    'Complete 500 missions',
    'flame',
  ],
  ['first-day', 'Cycle Initiated', 'Finalize your first System day.', 'Finalize 1 day', 'calendar'],
  ['seven-days', 'One Week Awake', 'Finalize seven System days.', 'Finalize 7 days', 'calendar'],
  [
    'thirty-days',
    'Month of Resolve',
    'Finalize thirty System days.',
    'Finalize 30 days',
    'calendar',
  ],
  [
    'hundred-days',
    'Long Campaign',
    'Finalize one hundred System days.',
    'Finalize 100 days',
    'calendar',
  ],
  [
    'year-recorded',
    'A Year in the Archive',
    'Finalize 365 System days.',
    'Finalize 365 days',
    'archive',
  ],
  [
    'first-perfect',
    'Perfect Day',
    'Complete every core mission in one cycle.',
    'Earn 1 Perfect Day',
    'diamond',
  ],
  [
    'five-perfect',
    'Pattern of Excellence',
    'Earn five Perfect Days.',
    'Earn 5 Perfect Days',
    'diamond',
  ],
  [
    'twenty-five-perfect',
    'Forged Routine',
    'Earn twenty-five Perfect Days.',
    'Earn 25 Perfect Days',
    'diamond',
  ],
  [
    'hundred-perfect',
    'Perfect Century',
    'Earn one hundred Perfect Days.',
    'Earn 100 Perfect Days',
    'crown',
  ],
  [
    'three-streak',
    'Momentum',
    'Maintain a three-day completion streak.',
    'Reach a 3-day streak',
    'flame',
  ],
  [
    'seven-streak',
    'Week Unbroken',
    'Maintain a seven-day completion streak.',
    'Reach a 7-day streak',
    'flame',
  ],
  [
    'thirty-streak',
    'Relentless',
    'Maintain a thirty-day completion streak.',
    'Reach a 30-day streak',
    'flame',
  ],
  [
    'ninety-streak',
    'Season Unbroken',
    'Maintain a ninety-day completion streak.',
    'Reach a 90-day streak',
    'flame',
  ],
  ['level-5', 'Awakening Confirmed', 'Reach account level 5.', 'Reach level 5', 'level'],
  ['level-10', 'Double Digits', 'Reach account level 10.', 'Reach level 10', 'level'],
  ['level-25', 'Proven Growth', 'Reach account level 25.', 'Reach level 25', 'level'],
  ['level-50', 'Half-Century Ascendant', 'Reach account level 50.', 'Reach level 50', 'level'],
  ['level-100', 'Limit Breaker', 'Reach account level 100.', 'Reach level 100', 'crown'],
  ['rank-e', 'E-Class Hunter', 'Advance to E-Class.', 'Reach E-Class', 'rank'],
  ['rank-d', 'D-Class Hunter', 'Advance to D-Class.', 'Reach D-Class', 'rank'],
  ['rank-c', 'C-Class Hunter', 'Advance to C-Class.', 'Reach C-Class', 'rank'],
  ['rank-b', 'B-Class Hunter', 'Advance to B-Class.', 'Reach B-Class', 'rank'],
  ['rank-a', 'A-Class Hunter', 'Advance to A-Class.', 'Reach A-Class', 'rank'],
  ['rank-s', 'S-Class Hunter', 'Advance to S-Class.', 'Reach S-Class', 'rank'],
  ['rank-world', 'World Class', 'Earn the final classification.', 'Reach World Class', 'crown'],
  ['faith-10', 'Rooted', 'Raise Faith to level 10.', 'Faith reaches level 10', 'faith'],
  [
    'strength-10',
    'Tempered',
    'Raise Strength to level 10.',
    'Strength reaches level 10',
    'strength',
  ],
  [
    'discipline-10',
    'Self-Command',
    'Raise Discipline to level 10.',
    'Discipline reaches level 10',
    'discipline',
  ],
  [
    'creativity-10',
    'Maker’s Path',
    'Raise Creativity to level 10.',
    'Creativity reaches level 10',
    'creativity',
  ],
  [
    'character-10',
    'Quiet Strength',
    'Raise Character to level 10.',
    'Character reaches level 10',
    'character',
  ],
  [
    'balanced-five',
    'Balanced Build',
    'Raise five stats to level 5.',
    'Five stats reach level 5',
    'balance',
  ],
  [
    'balanced-ten',
    'Complete Foundation',
    'Raise every stat to level 10.',
    'Every stat reaches level 10',
    'balance',
  ],
  [
    'first-weekly',
    'Weekly Victor',
    'Complete a weekly challenge.',
    'Complete 1 weekly challenge',
    'challenge',
  ],
  [
    'ten-weekly',
    'Campaign Specialist',
    'Complete ten weekly challenges.',
    'Complete 10 weekly challenges',
    'challenge',
  ],
  [
    'first-monthly',
    'Monthly Conqueror',
    'Complete a monthly challenge.',
    'Complete 1 monthly challenge',
    'challenge',
  ],
  [
    'first-boss',
    'Boss Defeated',
    'Complete a Boss Challenge.',
    'Complete 1 Boss Challenge',
    'boss',
  ],
  [
    'five-bosses',
    'Boss Hunter',
    'Complete five Boss Challenges.',
    'Complete 5 Boss Challenges',
    'boss',
  ],
  ['first-trial', 'Trial Passed', 'Complete a Class Trial.', 'Complete 1 Class Trial', 'trial'],
  [
    'recovery-started',
    'Wisdom to Recover',
    'Activate Recovery Mode.',
    'Activate Recovery Mode',
    'recovery',
  ],
  [
    'recovery-complete',
    'Return to Form',
    'Complete a recovery mission.',
    'Complete 1 recovery mission',
    'recovery',
  ],
  [
    'protected-day',
    'Grace Preserved',
    'Earn a protected Perfect Day.',
    'Earn 1 protected Perfect Day',
    'shield',
  ],
  ['first-backup', 'Archive Secured', 'Create a manual save backup.', 'Export a save', 'archive'],
  [
    'rare-signal',
    'Rare Signal Answered',
    'Complete an Emergency Quest.',
    'Complete 1 Emergency Quest',
    'spark',
  ],
  ['grace-token', 'Grace Received', 'Claim a rare Mission Pass.', 'Claim 1 Mission Pass', 'shield'],
  [
    'pass-wisely-used',
    'Wisdom Over Shame',
    'Use a Mission Pass to protect a difficult day.',
    'Use 1 Mission Pass',
    'recovery',
  ],
  ['customized', 'System Architect', 'Customize a mission.', 'Customize a mission', 'settings'],
  [
    'all-categories',
    'Whole-Life Build',
    'Complete a mission in every category.',
    'Complete every category',
    'balance',
  ],
  [
    'hidden-return',
    'Still Standing',
    'Return after a long break and complete a mission.',
    'Hidden',
    'unknown',
  ],
] as const;

const rarityFor = (index: number): Achievement['rarity'] =>
  index >= 49
    ? 'ascendant'
    : index >= 45
      ? 'legendary'
      : index >= 36
        ? 'epic'
        : index >= 23
          ? 'rare'
          : index >= 10
            ? 'uncommon'
            : 'common';

export const ACHIEVEMENTS: Achievement[] = DEFINITIONS.map(
  ([id, name, description, condition, icon], index) => ({
    id,
    name,
    description,
    condition,
    icon,
    hidden: id.startsWith('hidden-'),
    rarity: rarityFor(index),
  }),
);
