import type { RankRequirement, StatName } from '@/types/game';

export const BALANCE = {
  account: {
    baseXp: 150,
    growth: 0.85,
    linear: 30,
    perfectDayBonus: 50,
    protectedPerfectDayBonus: 25,
    recoveryMultiplier: 0.65,
    warningMultiplier: 0.9,
    minimumMultiplier: 0.75,
  },
  stats: {
    baseXp: 180,
    growth: 1.3,
    linear: 42,
    missionMomentumGain: 8,
    perfectDayMomentumGain: 4,
    firstMissMomentumLoss: 8,
    repeatedMissMomentumLoss: 13,
    decayThreshold: 35,
    smallDecayAfterDays: 3,
    strongerDecayAfterDays: 7,
    smallDecayXp: 4,
    strongerDecayXp: 8,
    minimumFloorRatio: 0.72,
    lifetimeFloorStep: 1000,
    recoveryDecayMultiplier: 0.2,
  },
  penalties: {
    warningMisses: 2,
    stagnantMisses: 5,
    recoveryReturnDays: 3,
  },
  protectedExceptionsPerMonth: 2,
  weeklyChallengeAccountXp: [100, 150, 220, 300, 420],
  monthlyChallengeAccountXp: [350, 500, 700, 950, 1250],
} as const;

export const PERFECT_DAY_STAT_REWARDS: Partial<Record<StatName, number>> = {
  discipline: 8,
  vitality: 6,
  character: 6,
};

export const RANK_ORDER = ['F', 'E', 'D', 'C', 'B', 'A', 'S', 'WORLD CLASS'] as const;

export const RANK_REQUIREMENTS: RankRequirement[] = [
  {
    rank: 'F',
    minimumLevel: 1,
    lifetimeCompletions: 0,
    completedDays: 0,
    disciplineLevel: 1,
    balancedStatLevel: 1,
    balancedStatsRequired: 0,
    challengesCompleted: 0,
  },
  {
    rank: 'E',
    minimumLevel: 10,
    lifetimeCompletions: 50,
    completedDays: 12,
    disciplineLevel: 3,
    balancedStatLevel: 2,
    balancedStatsRequired: 4,
    challengesCompleted: 1,
    trialTemplateId: 'trial-e',
  },
  {
    rank: 'D',
    minimumLevel: 20,
    lifetimeCompletions: 180,
    completedDays: 40,
    disciplineLevel: 6,
    balancedStatLevel: 3,
    balancedStatsRequired: 5,
    challengesCompleted: 4,
    trialTemplateId: 'trial-d',
  },
  {
    rank: 'C',
    minimumLevel: 32,
    lifetimeCompletions: 420,
    completedDays: 90,
    disciplineLevel: 10,
    balancedStatLevel: 5,
    balancedStatsRequired: 6,
    challengesCompleted: 8,
    trialTemplateId: 'trial-c',
  },
  {
    rank: 'B',
    minimumLevel: 40,
    lifetimeCompletions: 750,
    completedDays: 150,
    disciplineLevel: 13,
    balancedStatLevel: 7,
    balancedStatsRequired: 7,
    challengesCompleted: 15,
    trialTemplateId: 'trial-b',
  },
  {
    rank: 'A',
    minimumLevel: 50,
    lifetimeCompletions: 1300,
    completedDays: 240,
    disciplineLevel: 18,
    balancedStatLevel: 9,
    balancedStatsRequired: 8,
    challengesCompleted: 26,
    trialTemplateId: 'trial-a',
  },
  {
    rank: 'S',
    minimumLevel: 58,
    lifetimeCompletions: 2050,
    completedDays: 360,
    disciplineLevel: 22,
    balancedStatLevel: 12,
    balancedStatsRequired: 9,
    challengesCompleted: 38,
    trialTemplateId: 'trial-s',
  },
  {
    rank: 'WORLD CLASS',
    minimumLevel: 65,
    lifetimeCompletions: 2850,
    completedDays: 480,
    disciplineLevel: 26,
    balancedStatLevel: 14,
    balancedStatsRequired: 10,
    challengesCompleted: 55,
    trialTemplateId: 'trial-world',
  },
];
