import type { RankRequirement, StatName } from '@/types/game';

export const BALANCE = {
  account: {
    baseXp: 150,
    growth: 0.85,
    linear: 30,
    perfectDayBonus: 50,
    protectedPerfectDayBonus: 25,
    recoveryMultiplier: 0.65,
    warningMultiplier: 0.9,
    minimumMultiplier: 0.75,
  },
  stats: {
    baseXp: 180,
    growth: 1.3,
    linear: 42,
    missionMomentumGain: 8,
    perfectDayMomentumGain: 4,
    firstMissMomentumLoss: 8,
    repeatedMissMomentumLoss: 13,
    decayThreshold: 35,
    smallDecayAfterDays: 3,
    strongerDecayAfterDays: 7,
    smallDecayXp: 4,
    strongerDecayXp: 8,
    minimumFloorRatio: 0.72,
    lifetimeFloorStep: 1000,
    recoveryDecayMultiplier: 0.2,
  },
  penalties: {
    warningMisses: 2,
    stagnantMisses: 5,
    recoveryReturnDays: 3,
  },
  protectedExceptionsPerMonth: 2,
  weeklyChallengeAccountXp: [100, 150, 220, 300, 420],
  monthlyChallengeAccountXp: [350, 500, 700, 950, 1250],
} as const;

export const PERFECT_DAY_STAT_REWARDS: Partial<Record<StatName, number>> = {
  discipline: 8,
  vitality: 6,
  character: 6,
};

export const RANK_ORDER = ['F', 'E', 'D', 'C', 'B', 'A', 'S', 'WORLD CLASS'] as const;

export const RANK_REQUIREMENTS: RankRequirement[] = [
  {
    rank: 'F',
    minimumLevel: 1,
    lifetimeCompletions: 0,
    completedDays: 0,
    disciplineLevel: 1,
    balancedStatLevel: 1,
    balancedStatsRequired: 0,
    challengesCompleted: 0,
  },
  {
    rank: 'E',
    minimumLevel: 12,
    lifetimeCompletions: 150,
    completedDays: 25,
    disciplineLevel: 5,
    balancedStatLevel: 3,
    balancedStatsRequired: 4,
    challengesCompleted: 1,
    trialTemplateId: 'trial-e',
  },
  {
    rank: 'D',
    minimumLevel: 25,
    lifetimeCompletions: 650,
    completedDays: 100,
    disciplineLevel: 11,
    balancedStatLevel: 7,
    balancedStatsRequired: 5,
    challengesCompleted: 4,
    trialTemplateId: 'trial-d',
  },
  {
    rank: 'C',
    minimumLevel: 40,
    lifetimeCompletions: 1500,
    completedDays: 220,
    disciplineLevel: 20,
    balancedStatLevel: 13,
    balancedStatsRequired: 6,
    challengesCompleted: 10,
    trialTemplateId: 'trial-c',
  },
  {
    rank: 'B',
    minimumLevel: 58,
    lifetimeCompletions: 3800,
    completedDays: 520,
    disciplineLevel: 32,
    balancedStatLevel: 23,
    balancedStatsRequired: 7,
    challengesCompleted: 24,
    trialTemplateId: 'trial-b',
  },
  {
    rank: 'A',
    minimumLevel: 74,
    lifetimeCompletions: 6800,
    completedDays: 900,
    disciplineLevel: 45,
    balancedStatLevel: 34,
    balancedStatsRequired: 8,
    challengesCompleted: 42,
    trialTemplateId: 'trial-a',
  },
  {
    rank: 'S',
    minimumLevel: 96,
    lifetimeCompletions: 12000,
    completedDays: 1650,
    disciplineLevel: 62,
    balancedStatLevel: 49,
    balancedStatsRequired: 9,
    challengesCompleted: 75,
    trialTemplateId: 'trial-s',
  },
  {
    rank: 'WORLD CLASS',
    minimumLevel: 125,
    lifetimeCompletions: 20500,
    completedDays: 2850,
    disciplineLevel: 82,
    balancedStatLevel: 68,
    balancedStatsRequired: 10,
    challengesCompleted: 125,
    trialTemplateId: 'trial-world',
  },
];
