import type { ChallengeTemplate, MissionCategory, StatReward } from '@/types/game';

const rewardMap: Record<string, StatReward[]> = {
  faith: [
    { stat: 'faith', xp: 35 },
    { stat: 'wisdom', xp: 20 },
  ],
  discipline: [
    { stat: 'discipline', xp: 35 },
    { stat: 'willpower', xp: 25 },
  ],
  physical: [
    { stat: 'vitality', xp: 30 },
    { stat: 'endurance', xp: 25 },
  ],
  creator: [
    { stat: 'creativity', xp: 35 },
    { stat: 'focus', xp: 25 },
  ],
  character: [
    { stat: 'character', xp: 30 },
    { stat: 'empathy', xp: 25 },
  ],
  balanced: [
    { stat: 'discipline', xp: 20 },
    { stat: 'vitality', xp: 20 },
    { stat: 'character', xp: 20 },
  ],
};

const OPTIONAL_CHALLENGE_REWARD_MULTIPLIER = 1.5;

function boostOptionalChallengeRewards(challenge: ChallengeTemplate): ChallengeTemplate {
  return {
    ...challenge,
    accountXp: Math.round(challenge.accountXp * OPTIONAL_CHALLENGE_REWARD_MULTIPLIER),
    statRewards: challenge.statRewards.map((reward) => ({
      ...reward,
      xp: Math.round(reward.xp * OPTIONAL_CHALLENGE_REWARD_MULTIPLIER),
    })),
  };
}

function missionChallenge(
  id: string,
  name: string,
  description: string,
  kind: 'weekly' | 'monthly',
  category: MissionCategory | 'balanced',
  target: number,
  missionIds: string[],
  difficulty: ChallengeTemplate['difficulty'],
  accountXp: number,
): ChallengeTemplate {
  return {
    id,
    name,
    description,
    kind,
    category,
    difficulty,
    durationDays: kind === 'weekly' ? 7 : 31,
    requirement: { metric: 'mission-count', target, missionIds },
    accountXp,
    statRewards: rewardMap[category],
    protectedExceptions: difficulty === 'I' ? 1 : 0,
    milestones: [0.25, 0.5, 0.75, 1],
  };
}

function rateChallenge(
  id: string,
  name: string,
  description: string,
  kind: 'weekly' | 'monthly',
  rate: number,
  difficulty: ChallengeTemplate['difficulty'],
  accountXp: number,
): ChallengeTemplate {
  return {
    id,
    name,
    description,
    kind,
    category: 'balanced',
    difficulty,
    durationDays: kind === 'weekly' ? 7 : 31,
    requirement: { metric: 'completion-rate', target: Math.round(rate * 100), minimumRate: rate },
    accountXp,
    statRewards: rewardMap.balanced,
    protectedExceptions: difficulty === 'I' ? 1 : 0,
    milestones: [0.25, 0.5, 0.75, 1],
  };
}

const WEEKLY_CHALLENGE_DEFINITIONS: ChallengeTemplate[] = [
  {
    id: 'w-faith-6',
    name: 'Twin Lights',
    description: 'Complete Prayer and Bible together on 6 days.',
    kind: 'weekly',
    category: 'faith',
    difficulty: 'III',
    durationDays: 7,
    requirement: { metric: 'paired-days', target: 6, missionIds: ['prayer', 'bible'] },
    accountXp: 220,
    statRewards: rewardMap.faith,
    protectedExceptions: 1,
    milestones: [0.34, 0.5, 0.84, 1],
  },
  missionChallenge(
    'w-faith-10',
    'Quiet Sanctuary',
    'Complete 10 faith missions.',
    'weekly',
    'faith',
    10,
    ['prayer', 'bible'],
    'II',
    170,
  ),
  missionChallenge(
    'w-prayer-7',
    'Seven Invocations',
    'Complete Prayer on all 7 days.',
    'weekly',
    'faith',
    7,
    ['prayer'],
    'III',
    210,
  ),
  missionChallenge(
    'w-bible-6',
    'Living Pages',
    'Complete Bible on 6 days.',
    'weekly',
    'faith',
    6,
    ['bible'],
    'II',
    170,
  ),
  missionChallenge(
    'w-faith-8',
    'Foundation Stones',
    'Complete 8 faith missions.',
    'weekly',
    'faith',
    8,
    ['prayer', 'bible'],
    'I',
    130,
  ),
  missionChallenge(
    'w-integrity-7',
    'Quiet Resolve',
    'Complete 7 daily integrity missions.',
    'weekly',
    'discipline',
    7,
    ['no-porn'],
    'III',
    240,
  ),
  missionChallenge(
    'w-discipline-12',
    'Hold the Line',
    'Complete 12 discipline-linked missions.',
    'weekly',
    'discipline',
    12,
    ['no-porn', 'workout', 'creator-work'],
    'III',
    240,
  ),
  missionChallenge(
    'w-kind-5',
    'Signal of Grace',
    'Send 5 kind messages.',
    'weekly',
    'character',
    5,
    ['kind-message'],
    'II',
    160,
  ),
  missionChallenge(
    'w-kind-7',
    'Seven Signals',
    'Send one kind message each day.',
    'weekly',
    'character',
    7,
    ['kind-message'],
    'III',
    210,
  ),
  missionChallenge(
    'w-move-7',
    'Seven Gates',
    'Complete 7 Training Hall deployments.',
    'weekly',
    'physical',
    7,
    ['workout'],
    'III',
    220,
  ),
  missionChallenge(
    'w-move-5',
    'Kinetic Week',
    'Complete 5 Training Hall deployments.',
    'weekly',
    'physical',
    5,
    ['workout'],
    'I',
    130,
  ),
  missionChallenge(
    'w-workout-4',
    'Tempering Cycle',
    'Complete 4 workouts.',
    'weekly',
    'physical',
    4,
    ['workout'],
    'III',
    220,
  ),
  missionChallenge(
    'w-workout-3',
    'Strength Pattern',
    'Complete 3 workouts.',
    'weekly',
    'physical',
    3,
    ['workout'],
    'II',
    170,
  ),
  missionChallenge(
    'w-physical-9',
    'Body Alignment',
    'Complete 6 Training Hall deployments.',
    'weekly',
    'physical',
    6,
    ['workout'],
    'III',
    230,
  ),
  missionChallenge(
    'w-physical-7',
    'Vital Current',
    'Complete 5 Training Hall deployments.',
    'weekly',
    'physical',
    5,
    ['workout'],
    'II',
    180,
  ),
  missionChallenge(
    'w-creator-5',
    'Creator in Motion',
    'Complete 5 creator sessions.',
    'weekly',
    'creator',
    5,
    ['creator-work'],
    'III',
    220,
  ),
  missionChallenge(
    'w-creator-4',
    'Forge Hours',
    'Complete 4 creator sessions.',
    'weekly',
    'creator',
    4,
    ['creator-work'],
    'II',
    170,
  ),
  missionChallenge(
    'w-creator-3',
    'Open the Forge',
    'Complete 3 creator sessions.',
    'weekly',
    'creator',
    3,
    ['creator-work'],
    'I',
    130,
  ),
  missionChallenge(
    'w-balanced-21',
    'Threefold Rhythm',
    'Complete 21 missions of any kind.',
    'weekly',
    'balanced',
    21,
    [],
    'II',
    180,
  ),
  missionChallenge(
    'w-balanced-28',
    'Full Spectrum',
    'Complete 28 missions of any kind.',
    'weekly',
    'balanced',
    28,
    [],
    'III',
    250,
  ),
  missionChallenge(
    'w-balanced-35',
    'High Synchronization',
    'Complete 35 missions of any kind.',
    'weekly',
    'balanced',
    35,
    [],
    'IV',
    330,
  ),
  rateChallenge(
    'w-rate-70',
    'Stable Trajectory',
    'Reach 70% weekly completion.',
    'weekly',
    0.7,
    'I',
    140,
  ),
  rateChallenge(
    'w-rate-80',
    'Measured Advance',
    'Reach 80% weekly completion.',
    'weekly',
    0.8,
    'II',
    190,
  ),
  rateChallenge(
    'w-rate-85',
    'Precision Week',
    'Reach 85% weekly completion.',
    'weekly',
    0.85,
    'III',
    240,
  ),
  rateChallenge(
    'w-rate-90',
    'Near Totality',
    'Reach 90% weekly completion.',
    'weekly',
    0.9,
    'IV',
    320,
  ),
  {
    id: 'w-perfect-2',
    name: 'Two Complete Cycles',
    description: 'Achieve 2 Perfect Days.',
    kind: 'weekly',
    category: 'balanced',
    difficulty: 'II',
    durationDays: 7,
    requirement: { metric: 'perfect-days', target: 2 },
    accountXp: 180,
    statRewards: rewardMap.balanced,
    protectedExceptions: 0,
    milestones: [0.5, 1],
  },
  {
    id: 'w-perfect-3',
    name: 'Triad of Completion',
    description: 'Achieve 3 Perfect Days.',
    kind: 'weekly',
    category: 'balanced',
    difficulty: 'III',
    durationDays: 7,
    requirement: { metric: 'perfect-days', target: 3 },
    accountXp: 250,
    statRewards: rewardMap.balanced,
    protectedExceptions: 0,
    milestones: [0.34, 0.67, 1],
  },
  {
    id: 'w-perfect-5',
    name: 'Dominant Pattern',
    description: 'Achieve 5 Perfect Days.',
    kind: 'weekly',
    category: 'balanced',
    difficulty: 'V',
    durationDays: 7,
    requirement: { metric: 'perfect-days', target: 5 },
    accountXp: 440,
    statRewards: rewardMap.balanced,
    titleRewardId: 'the-consistent',
    protectedExceptions: 0,
    milestones: [0.2, 0.4, 0.6, 0.8, 1],
  },
  {
    id: 'w-paired-5',
    name: 'Mind and Body',
    description: 'Complete at least one faith and one physical mission on 5 days.',
    kind: 'weekly',
    category: 'balanced',
    difficulty: 'III',
    durationDays: 7,
    requirement: {
      metric: 'paired-days',
      target: 5,
      missionIds: ['prayer', 'bible', 'workout'],
    },
    accountXp: 240,
    statRewards: rewardMap.balanced,
    protectedExceptions: 1,
    milestones: [0.4, 0.6, 0.8, 1],
  },
  {
    id: 'w-recovery',
    name: 'Return Vector',
    description: 'After an incomplete day, complete every active core mission the next day.',
    kind: 'weekly',
    category: 'recovery',
    difficulty: 'III',
    durationDays: 7,
    requirement: { metric: 'recovery', target: 1 },
    accountXp: 220,
    statRewards: rewardMap.discipline,
    titleRewardId: 'returning-hunter',
    protectedExceptions: 0,
    milestones: [1],
  },
];

export const WEEKLY_CHALLENGES = WEEKLY_CHALLENGE_DEFINITIONS.map(boostOptionalChallengeRewards);

const MONTHLY_CHALLENGE_DEFINITIONS: ChallengeTemplate[] = [
  missionChallenge(
    'm-workout-12',
    'Tempered Frame',
    'Complete 12 workouts this month.',
    'monthly',
    'physical',
    12,
    ['workout'],
    'II',
    500,
  ),
  missionChallenge(
    'm-workout-16',
    'Iron Calendar',
    'Complete 16 workouts this month.',
    'monthly',
    'physical',
    16,
    ['workout'],
    'III',
    700,
  ),
  missionChallenge(
    'm-workout-20',
    'Body Forged',
    'Complete 20 workouts this month.',
    'monthly',
    'physical',
    20,
    ['workout'],
    'V',
    1150,
  ),
  missionChallenge(
    'm-move-20',
    'Long Current',
    'Complete 14 Training Hall deployments.',
    'monthly',
    'physical',
    14,
    ['workout'],
    'II',
    500,
  ),
  missionChallenge(
    'm-move-25',
    'Restless Horizon',
    'Complete 18 Training Hall deployments.',
    'monthly',
    'physical',
    18,
    ['workout'],
    'III',
    700,
  ),
  missionChallenge(
    'm-prayer-20',
    'Sustained Prayer',
    'Complete 20 prayer missions.',
    'monthly',
    'faith',
    20,
    ['prayer'],
    'II',
    500,
  ),
  missionChallenge(
    'm-prayer-25',
    'Inner Sanctuary',
    'Complete 25 prayer missions.',
    'monthly',
    'faith',
    25,
    ['prayer'],
    'III',
    700,
  ),
  missionChallenge(
    'm-bible-20',
    'Twenty Studies',
    'Complete 20 Bible missions.',
    'monthly',
    'faith',
    20,
    ['bible'],
    'II',
    500,
  ),
  missionChallenge(
    'm-bible-25',
    'Written Foundation',
    'Complete 25 Bible missions.',
    'monthly',
    'faith',
    25,
    ['bible'],
    'III',
    700,
  ),
  missionChallenge(
    'm-faith-45',
    'Deep Roots',
    'Complete 45 faith missions.',
    'monthly',
    'faith',
    45,
    ['prayer', 'bible'],
    'IV',
    900,
  ),
  missionChallenge(
    'm-creator-16',
    'Active Forge',
    'Complete 16 creator sessions.',
    'monthly',
    'creator',
    16,
    ['creator-work'],
    'II',
    520,
  ),
  missionChallenge(
    'm-creator-20',
    'Architect’s Month',
    'Complete 20 creator sessions.',
    'monthly',
    'creator',
    20,
    ['creator-work'],
    'III',
    720,
  ),
  missionChallenge(
    'm-kind-20',
    'Echoes of Good',
    'Complete 20 kind messages.',
    'monthly',
    'character',
    20,
    ['kind-message'],
    'II',
    500,
  ),
  missionChallenge(
    'm-kind-25',
    'Beacon Network',
    'Complete 25 kind messages.',
    'monthly',
    'character',
    25,
    ['kind-message'],
    'III',
    700,
  ),
  missionChallenge(
    'm-integrity-25',
    'Quiet Discipline',
    'Complete 25 daily integrity missions.',
    'monthly',
    'discipline',
    25,
    ['no-porn'],
    'IV',
    850,
  ),
  rateChallenge(
    'm-rate-75',
    'Stable Month',
    'Reach 75% monthly completion.',
    'monthly',
    0.75,
    'II',
    550,
  ),
  rateChallenge(
    'm-rate-80',
    'Aligned Month',
    'Reach 80% monthly completion.',
    'monthly',
    0.8,
    'III',
    750,
  ),
  rateChallenge(
    'm-rate-85',
    'Ascending Month',
    'Reach 85% monthly completion.',
    'monthly',
    0.85,
    'IV',
    1000,
  ),
  {
    id: 'm-perfect-10',
    name: 'Ten Complete Days',
    description: 'Achieve 10 Perfect Days this month.',
    kind: 'monthly',
    category: 'balanced',
    difficulty: 'III',
    durationDays: 31,
    requirement: { metric: 'perfect-days', target: 10 },
    accountXp: 760,
    statRewards: rewardMap.balanced,
    titleRewardId: 'keeper-of-momentum',
    protectedExceptions: 1,
    milestones: [0.3, 0.5, 0.8, 1],
  },
  {
    id: 'm-balanced',
    name: 'Fivefold Balance',
    description: 'Complete at least 12 missions in each major category.',
    kind: 'monthly',
    category: 'balanced',
    difficulty: 'IV',
    durationDays: 31,
    requirement: { metric: 'balanced-thresholds', target: 5, secondaryTarget: 12 },
    accountXp: 1050,
    statRewards: rewardMap.balanced,
    titleRewardId: 'balanced-ascendant',
    cosmeticReward: 'sigil-prism',
    protectedExceptions: 1,
    milestones: [0.2, 0.4, 0.6, 0.8, 1],
  },
];

export const MONTHLY_CHALLENGES = MONTHLY_CHALLENGE_DEFINITIONS.map(boostOptionalChallengeRewards);

const BOSS_CHALLENGE_DEFINITIONS: ChallengeTemplate[] = [
  {
    id: 'boss-awakening',
    name: 'Seven-Day Awakening',
    description: 'Complete at least 80% of missions for 7 days.',
    kind: 'boss',
    category: 'balanced',
    difficulty: 'II',
    durationDays: 7,
    requirement: { metric: 'completion-rate', target: 80, minimumRate: 0.8 },
    accountXp: 450,
    statRewards: rewardMap.balanced,
    titleRewardId: 'awakened-in-motion',
    protectedExceptions: 1,
    milestones: [0.25, 0.5, 0.75, 1],
  },
  {
    id: 'boss-discipline',
    name: 'Discipline Protocol',
    description: 'Complete the daily integrity mission for 14 consecutive days.',
    kind: 'boss',
    category: 'discipline',
    difficulty: 'III',
    durationDays: 14,
    requirement: { metric: 'mission-count', target: 14, missionIds: ['no-porn'] },
    accountXp: 750,
    statRewards: rewardMap.discipline,
    titleRewardId: 'quiet-resolve',
    protectedExceptions: 1,
    milestones: [0.25, 0.5, 0.75, 1],
  },
  {
    id: 'boss-creator',
    name: 'Creator’s Forge',
    description: 'Complete 10 creator sessions within 14 days.',
    kind: 'boss',
    category: 'creator',
    difficulty: 'III',
    durationDays: 14,
    requirement: { metric: 'mission-count', target: 10, missionIds: ['creator-work'] },
    accountXp: 720,
    statRewards: rewardMap.creator,
    titleRewardId: 'architect-of-worlds',
    protectedExceptions: 1,
    milestones: [0.3, 0.5, 0.8, 1],
  },
  {
    id: 'boss-body',
    name: 'Body Tempering',
    description: 'Complete 12 Training Hall deployments within 14 days.',
    kind: 'boss',
    category: 'physical',
    difficulty: 'IV',
    durationDays: 14,
    requirement: { metric: 'mission-count', target: 12, missionIds: ['workout'] },
    accountXp: 900,
    statRewards: rewardMap.physical,
    titleRewardId: 'tempered-vessel',
    protectedExceptions: 1,
    milestones: [0.25, 0.5, 0.75, 1],
  },
  {
    id: 'boss-faith',
    name: 'Faith Foundation',
    description: 'Complete Prayer and Bible on 14 of 16 days.',
    kind: 'boss',
    category: 'faith',
    difficulty: 'IV',
    durationDays: 16,
    requirement: { metric: 'paired-days', target: 14, missionIds: ['prayer', 'bible'] },
    accountXp: 950,
    statRewards: rewardMap.faith,
    titleRewardId: 'faithful-initiate',
    protectedExceptions: 2,
    milestones: [0.25, 0.5, 0.75, 1],
  },
  {
    id: 'boss-ascension',
    name: 'Thirty-Day Ascension',
    description: 'Achieve at least 85% completion across 30 days.',
    kind: 'boss',
    category: 'balanced',
    difficulty: 'V',
    durationDays: 30,
    requirement: { metric: 'completion-rate', target: 85, minimumRate: 0.85 },
    accountXp: 1800,
    statRewards: rewardMap.balanced,
    titleRewardId: 'thirty-day-ascendant',
    cosmeticReward: 'frame-ascension',
    protectedExceptions: 2,
    milestones: [0.2, 0.4, 0.6, 0.8, 1],
  },
];

export const BOSS_CHALLENGES = BOSS_CHALLENGE_DEFINITIONS.map(boostOptionalChallengeRewards);

const RECOVERY_CHALLENGE_DEFINITIONS: ChallengeTemplate[] = [
  missionChallenge(
    'recovery-one',
    'Recovery Step',
    'Complete one core mission today.',
    'weekly',
    'balanced',
    1,
    [],
    'I',
    20,
  ),
  missionChallenge(
    'recovery-walk',
    'Training Hall Return',
    'Complete the Daily Workout through any Training Hall path.',
    'weekly',
    'physical',
    1,
    ['workout'],
    'I',
    20,
  ),
  missionChallenge(
    'recovery-prayer',
    'Quiet Return',
    'Complete Prayer today.',
    'weekly',
    'faith',
    1,
    ['prayer'],
    'I',
    20,
  ),
  missionChallenge(
    'recovery-bible',
    'One Passage',
    'Complete Bible today.',
    'weekly',
    'faith',
    1,
    ['bible'],
    'I',
    20,
  ),
  missionChallenge(
    'recovery-creator',
    'Ten-Minute Forge',
    'Complete one small creator session today.',
    'weekly',
    'creator',
    1,
    ['creator-work'],
    'I',
    20,
  ),
  missionChallenge(
    'recovery-kind',
    'Honest Signal',
    'Send one sincere message today.',
    'weekly',
    'character',
    1,
    ['kind-message'],
    'I',
    20,
  ),
  missionChallenge(
    'recovery-breath',
    'Five Quiet Minutes',
    'Complete a brief prayer or reflection session today.',
    'weekly',
    'faith',
    1,
    ['prayer'],
    'I',
    20,
  ),
  missionChallenge(
    'recovery-outside',
    'Open Air',
    'Complete one Training Hall deployment today.',
    'weekly',
    'physical',
    1,
    ['workout'],
    'I',
    20,
  ),
  missionChallenge(
    'recovery-create',
    'One Small Piece',
    'Complete a deliberately small creator task today.',
    'weekly',
    'creator',
    1,
    ['creator-work'],
    'I',
    20,
  ),
  missionChallenge(
    'recovery-anchor',
    'Single Anchor',
    'Complete any one enabled core mission today.',
    'weekly',
    'balanced',
    1,
    [],
    'I',
    20,
  ),
].map((challenge) => ({
  ...challenge,
  kind: 'recovery' as const,
  durationDays: 1,
  accountXp: 20,
  statRewards: [{ stat: 'discipline' as const, xp: 5 }],
}));

export const RECOVERY_CHALLENGES = RECOVERY_CHALLENGE_DEFINITIONS.map(
  boostOptionalChallengeRewards,
);

export const RANK_TRIALS: ChallengeTemplate[] = [
  {
    id: 'trial-e',
    name: 'E-Class Trial · First Classification',
    description: 'Complete 5 of the next 7 days with no failed core missions.',
    kind: 'rank-trial',
    category: 'rank',
    difficulty: 'II',
    durationDays: 7,
    requirement: { metric: 'trial-days', target: 5, minimumRate: 1 },
    accountXp: 500,
    statRewards: rewardMap.balanced,
    protectedExceptions: 1,
    milestones: [0.4, 0.6, 0.8, 1],
    rankTarget: 'E',
  },
  {
    id: 'trial-d',
    name: 'D-Class Trial · Twin Pillars',
    description: 'Complete 10 workouts and 10 faith missions within 21 days.',
    kind: 'rank-trial',
    category: 'rank',
    difficulty: 'III',
    durationDays: 21,
    requirement: {
      metric: 'balanced-thresholds',
      target: 2,
      missionIds: ['workout', 'prayer', 'bible'],
      groups: [
        { missionIds: ['workout'], target: 10 },
        { missionIds: ['prayer', 'bible'], target: 10 },
      ],
    },
    accountXp: 950,
    statRewards: rewardMap.balanced,
    protectedExceptions: 2,
    milestones: [0.25, 0.5, 0.75, 1],
    rankTarget: 'D',
  },
  {
    id: 'trial-c',
    name: 'C-Class Trial · Thirty-Day Campaign',
    description: 'Complete a 30-day campaign at 85% or higher.',
    kind: 'rank-trial',
    category: 'rank',
    difficulty: 'IV',
    durationDays: 30,
    requirement: { metric: 'completion-rate', target: 85, minimumRate: 0.85 },
    accountXp: 1700,
    statRewards: rewardMap.balanced,
    protectedExceptions: 2,
    milestones: [0.25, 0.5, 0.75, 1],
    rankTarget: 'C',
  },
  {
    id: 'trial-b',
    name: 'B-Class Trial · Balanced Campaign',
    description: 'Sustain an 87% rate across a balanced 35-day campaign.',
    kind: 'rank-trial',
    category: 'rank',
    difficulty: 'IV',
    durationDays: 35,
    requirement: { metric: 'completion-rate', target: 87, minimumRate: 0.87 },
    accountXp: 2600,
    statRewards: rewardMap.balanced,
    protectedExceptions: 3,
    milestones: [0.2, 0.4, 0.6, 0.8, 1],
    rankTarget: 'B',
  },
  {
    id: 'trial-a',
    name: 'A-Class Trial · Forty-Five-Day Crucible',
    description: 'Complete a 45-day campaign with 90% completion and balanced growth.',
    kind: 'rank-trial',
    category: 'rank',
    difficulty: 'V',
    durationDays: 45,
    requirement: { metric: 'completion-rate', target: 90, minimumRate: 0.9 },
    accountXp: 4000,
    statRewards: rewardMap.balanced,
    protectedExceptions: 3,
    milestones: [0.2, 0.4, 0.6, 0.8, 1],
    rankTarget: 'A',
  },
  {
    id: 'trial-s',
    name: 'S-Class Trial · Sixty-Day Threshold',
    description: 'Complete a strict 60-day campaign at 92% or higher.',
    kind: 'rank-trial',
    category: 'rank',
    difficulty: 'V',
    durationDays: 60,
    requirement: { metric: 'completion-rate', target: 92, minimumRate: 0.92 },
    accountXp: 6500,
    statRewards: rewardMap.balanced,
    protectedExceptions: 4,
    milestones: [0.2, 0.4, 0.6, 0.8, 1],
    rankTarget: 'S',
  },
  {
    id: 'trial-world',
    name: 'World Class Trial · Six Gates',
    description: 'Complete a multi-stage 90-day campaign at 94% or higher.',
    kind: 'rank-trial',
    category: 'rank',
    difficulty: 'V',
    durationDays: 90,
    requirement: { metric: 'completion-rate', target: 94, minimumRate: 0.94 },
    accountXp: 12000,
    statRewards: rewardMap.balanced,
    protectedExceptions: 6,
    milestones: [0.16, 0.33, 0.5, 0.66, 0.83, 1],
    rankTarget: 'WORLD CLASS',
  },
];

export const ALL_CHALLENGE_TEMPLATES = [
  ...WEEKLY_CHALLENGES,
  ...MONTHLY_CHALLENGES,
  ...BOSS_CHALLENGES,
  ...RECOVERY_CHALLENGES,
  ...RANK_TRIALS,
];

export function getChallengeTemplate(id: string) {
  return ALL_CHALLENGE_TEMPLATES.find((challenge) => challenge.id === id);
}
