import type { CosmeticDefinition } from '@/types/game';

export const COSMETICS: CosmeticDefinition[] = [
  {
    id: 'frame-origin',
    name: 'Origin Frame',
    description: 'The first border carried by every candidate.',
    kind: 'frame',
    rarity: 'common',
    unlockCondition: 'Create a profile',
    previewClass: 'frame-origin',
  },
  {
    id: 'frame-faith',
    name: 'Covenant Frame',
    description: 'A restrained gold and mint profile edge.',
    kind: 'frame',
    rarity: 'uncommon',
    unlockCondition: 'Reach Faith level 10',
    previewClass: 'focus-faith',
  },
  {
    id: 'frame-discipline',
    name: 'Iron Resolve',
    description: 'A cold steel frame for consistent discipline.',
    kind: 'frame',
    rarity: 'rare',
    unlockCondition: 'Reach a 30-day cleared-day streak',
    previewClass: 'focus-discipline',
  },
  {
    id: 'frame-physical',
    name: 'Tempered Body',
    description: 'A crimson-edged frame earned through movement.',
    kind: 'frame',
    rarity: 'rare',
    unlockCondition: 'Reach Strength level 15',
    previewClass: 'focus-physical',
  },
  {
    id: 'frame-creator',
    name: 'Architect',
    description: 'A violet frame for sustained creative output.',
    kind: 'frame',
    rarity: 'rare',
    unlockCondition: 'Reach Creativity level 15',
    previewClass: 'focus-creator',
  },
  {
    id: 'sigil-origin',
    name: 'Origin Sigil',
    description: 'The System’s initial mark.',
    kind: 'sigil',
    rarity: 'common',
    unlockCondition: 'Create a profile',
    previewClass: 'sigil-origin',
  },
  {
    id: 'sigil-seven',
    name: 'Seven-Day Sigil',
    description: 'A seven-point mark for an unbroken week.',
    kind: 'sigil',
    rarity: 'uncommon',
    unlockCondition: 'Reach a 7-day cleared-day streak',
    previewClass: 'sigil-seven',
  },
  {
    id: 'sigil-perfect',
    name: 'Perfect Sigil',
    description: 'A luminous mark reserved for exact execution.',
    kind: 'sigil',
    rarity: 'epic',
    unlockCondition: 'Earn 25 Perfect Days',
    previewClass: 'sigil-perfect',
  },
  {
    id: 'theme-void',
    name: 'Quiet Void',
    description: 'A low-glow interface palette.',
    kind: 'theme',
    rarity: 'uncommon',
    unlockCondition: 'Finalize 30 days',
    previewClass: 'theme-void',
  },
  {
    id: 'theme-ascendant',
    name: 'Ascendant Violet',
    description: 'A vivid violet interface for higher classifications.',
    kind: 'theme',
    rarity: 'legendary',
    unlockCondition: 'Reach A-Class',
    previewClass: 'theme-ascendant',
  },
  {
    id: 'sigil-prism',
    name: 'Prism Sigil',
    description: 'A many-sided sigil earned from a balanced campaign.',
    kind: 'sigil',
    rarity: 'epic',
    unlockCondition: 'Complete Prism Campaign',
    previewClass: 'sigil-prism',
  },
  {
    id: 'frame-ascension',
    name: 'Ascension Frame',
    description: 'A high-tier frame for a sustained thirty-day operation.',
    kind: 'frame',
    rarity: 'legendary',
    unlockCondition: 'Complete Ascension Protocol',
    previewClass: 'frame-ascension',
  },
];
