import type { MissionDefinition } from '@/types/game';

export const DEFAULT_MISSIONS: MissionDefinition[] = [
  {
    id: 'prayer',
    name: 'Prayer',
    shortName: 'Prayer',
    description: 'Spend intentional time in prayer.',
    category: 'faith',
    method: 'toggle',
    accountXp: 20,
    statRewards: [
      { stat: 'faith', xp: 14 },
      { stat: 'discipline', xp: 5 },
    ],
    enabled: true,
    isCore: true,
    allowNotes: true,
    detailFields: ['note'],
    recoveryEligible: true,
  },
  {
    id: 'bible',
    name: 'Bible',
    shortName: 'Bible',
    description: 'Read or study Scripture.',
    category: 'faith',
    method: 'toggle',
    accountXp: 25,
    statRewards: [
      { stat: 'faith', xp: 10 },
      { stat: 'wisdom', xp: 12 },
      { stat: 'focus', xp: 4 },
    ],
    enabled: true,
    isCore: true,
    allowNotes: true,
    detailFields: ['passage', 'note'],
    recoveryEligible: true,
  },
  {
    id: 'no-porn',
    name: 'No Porn',
    shortName: 'Integrity',
    description: 'Complete the entire day without pornography.',
    category: 'discipline',
    method: 'day-boundary',
    accountXp: 40,
    statRewards: [
      { stat: 'discipline', xp: 18 },
      { stat: 'willpower', xp: 16 },
    ],
    enabled: true,
    isCore: true,
    allowNotes: false,
    detailFields: ['eveningStatus'],
    recoveryEligible: false,
  },
  {
    id: 'kind-message',
    name: 'One Kind Message',
    shortName: 'Kindness',
    description: 'Send one sincere and encouraging message to another person.',
    category: 'character',
    method: 'toggle',
    accountXp: 20,
    statRewards: [
      { stat: 'character', xp: 12 },
      { stat: 'empathy', xp: 14 },
    ],
    enabled: true,
    isCore: true,
    allowNotes: true,
    detailFields: ['recipient', 'note'],
    recoveryEligible: true,
  },
  {
    id: 'workout',
    name: 'Daily Workout',
    shortName: 'Workout',
    description:
      'Enter the Training Hall for a home circuit, gym deployment, conditioning mission, or recovery protocol.',
    category: 'physical',
    method: 'toggle',
    accountXp: 75,
    statRewards: [
      { stat: 'strength', xp: 18 },
      { stat: 'endurance', xp: 14 },
      { stat: 'discipline', xp: 8 },
      { stat: 'vitality', xp: 22 },
    ],
    enabled: true,
    isCore: true,
    allowNotes: true,
    detailFields: ['workoutType', 'duration', 'difficulty', 'note'],
    recoveryEligible: false,
  },
  {
    id: 'creator-work',
    name: 'YouTube / ARC Work',
    shortName: 'Creator Work',
    description: 'Make meaningful progress on YouTube content or the ARC creative universe.',
    category: 'creator',
    method: 'choice',
    accountXp: 35,
    statRewards: [
      { stat: 'creativity', xp: 16 },
      { stat: 'focus', xp: 12 },
      { stat: 'discipline', xp: 6 },
    ],
    enabled: true,
    isCore: true,
    allowNotes: true,
    detailFields: ['creatorChoice', 'minutes', 'workPerformed', 'note'],
    recoveryEligible: true,
  },
];

export const OPTIONAL_MISSION_TEMPLATES: MissionDefinition[] = [
  {
    id: 'template-hydration',
    name: 'Hydration',
    shortName: 'Water',
    description: 'Reach the water target you set for the day.',
    category: 'physical',
    method: 'numeric',
    accountXp: 10,
    statRewards: [{ stat: 'vitality', xp: 6 }],
    enabled: false,
    isCore: false,
    optional: true,
    allowNotes: true,
    detailFields: ['quantity', 'note'],
    numericUnit: 'glasses',
    numericTarget: 8,
    recoveryEligible: true,
  },
  {
    id: 'template-sleep',
    name: 'Sleep Routine',
    shortName: 'Sleep',
    description: 'Follow the wind-down and sleep routine you chose.',
    category: 'physical',
    method: 'toggle',
    accountXp: 10,
    statRewards: [{ stat: 'vitality', xp: 6 }],
    enabled: false,
    isCore: false,
    optional: true,
    allowNotes: true,
    detailFields: ['note'],
    recoveryEligible: true,
  },
  {
    id: 'template-journal',
    name: 'Journal',
    shortName: 'Journal',
    description: 'Write a short honest reflection.',
    category: 'character',
    method: 'toggle',
    accountXp: 10,
    statRewards: [{ stat: 'wisdom', xp: 5 }],
    enabled: false,
    isCore: false,
    optional: true,
    allowNotes: true,
    detailFields: ['note'],
    recoveryEligible: true,
  },
  {
    id: 'template-reading',
    name: 'Focused Reading',
    shortName: 'Reading',
    description: 'Read without distraction for your chosen duration.',
    category: 'discipline',
    method: 'duration',
    accountXp: 12,
    statRewards: [{ stat: 'focus', xp: 7 }],
    enabled: false,
    isCore: false,
    optional: true,
    allowNotes: true,
    detailFields: ['minutes', 'note'],
    recoveryEligible: true,
  },
  {
    id: 'template-learning',
    name: 'Skill Practice',
    shortName: 'Practice',
    description: 'Practice one useful skill deliberately.',
    category: 'creator',
    method: 'duration',
    accountXp: 12,
    statRewards: [{ stat: 'creativity', xp: 7 }],
    enabled: false,
    isCore: false,
    optional: true,
    allowNotes: true,
    detailFields: ['minutes', 'note'],
    recoveryEligible: true,
  },
];

export const CATEGORY_LABELS = {
  faith: 'Faith',
  discipline: 'Discipline',
  physical: 'Physical',
  creator: 'Creator',
  character: 'Character',
} as const;
