import type { CompanionId, SanctuaryConcern } from '@/types/game';

export interface SanctuaryConcernDefinition {
  id: SanctuaryConcern;
  label: string;
  prompt: string;
  description: string;
  companionId: CompanionId;
  strongholdAction: string;
}

export interface ScripturePassageDefinition {
  id: string;
  concern: SanctuaryConcern;
  reference: string;
  theme: string;
  context: string;
  observe: string;
  apply: string;
  prayer: string;
}

export const SANCTUARY_CONCERNS: SanctuaryConcernDefinition[] = [
  {
    id: 'sexual-integrity',
    label: 'Temptation & sexual integrity',
    prompt: 'I am fighting an urge or a pattern I do not want to obey.',
    description: 'Desire, escape, explicit content, boundaries, and honoring bodies without shame.',
    companionId: 'amara',
    strongholdAction:
      'Leave the private space, put the triggering device out of reach, and choose visible movement for ten minutes.',
  },
  {
    id: 'shame',
    label: 'Shame & guilt',
    prompt: 'I feel condemned, dirty, exposed, or unable to come back.',
    description: 'Honest confession, grace, repair, and returning without self-hatred.',
    companionId: 'snow',
    strongholdAction:
      'Name the specific action without naming yourself as the action, then choose one honest repair step.',
  },
  {
    id: 'anger',
    label: 'Anger & hatred',
    prompt: 'I am angry, resentful, hostile, or replaying what someone did.',
    description: 'Slowing reaction, pursuing justice without vengeance, and refusing bitterness.',
    companionId: 'ember',
    strongholdAction:
      'Create physical distance from the conflict and delay every message or decision until your body settles.',
  },
  {
    id: 'sadness',
    label: 'Sadness & depression',
    prompt: 'I feel heavy, hopeless, exhausted, or unable to explain the sadness.',
    description: 'Lament, receiving care, small next steps, and hope that does not deny pain.',
    companionId: 'snow',
    strongholdAction:
      'Move toward light, water, food, or a safe person; make the next action bodily small and concrete.',
  },
  {
    id: 'loneliness',
    label: 'Loneliness & rejection',
    prompt: 'I want closeness, feel unwanted, or am trying to numb being alone.',
    description:
      'Belonging, honest connection, healthy intimacy, and asking for presence directly.',
    companionId: 'amara',
    strongholdAction:
      'Send one honest, low-pressure message to a trustworthy person or move into a shared public space.',
  },
  {
    id: 'stress',
    label: 'Stress & anxiety',
    prompt: 'My mind is racing, my body is tense, or everything feels urgent.',
    description: 'Trust, limits, wise planning, breathing room, and releasing imagined control.',
    companionId: 'snow',
    strongholdAction:
      'Write the next necessary action and deliberately release every task that does not belong to this hour.',
  },
  {
    id: 'numbness',
    label: 'Numbness & apathy',
    prompt: 'I feel spiritually flat, detached, unmotivated, or unable to care.',
    description: 'Returning before feelings return, honest hunger, renewal, and gentle obedience.',
    companionId: 'snow',
    strongholdAction:
      'Do one embodied act of return: stand, open the passage, speak one honest sentence, and remain for five minutes.',
  },
  {
    id: 'focus',
    label: 'Difficulty focusing on God',
    prompt: 'My prayer is rushed, my attention scatters, or I keep avoiding quiet.',
    description:
      'Attention, solitude, Scripture meditation, consistency, and removing distraction.',
    companionId: 'cipher',
    strongholdAction:
      'Silence notifications, place the phone face down, and give one passage ten uninterrupted minutes.',
  },
  {
    id: 'doubt',
    label: 'Doubt & spiritual distance',
    prompt: 'God feels far away, I have questions, or belief feels difficult.',
    description:
      'Bringing questions into faith, remembering, waiting, and receiving patient evidence.',
    companionId: 'selah',
    strongholdAction:
      'Write the question exactly as it is and bring it to God without editing it into something more respectable.',
  },
  {
    id: 'forgiveness',
    label: 'Forgiveness & relational pain',
    prompt: 'I am carrying injury, bitterness, regret, or an unresolved relationship.',
    description: 'Grace, boundaries, release, reconciliation when safe, and freedom from revenge.',
    companionId: 'amara',
    strongholdAction:
      'Separate forgiveness from immediate access; release revenge while keeping every boundary required for safety.',
  },
  {
    id: 'identity',
    label: 'Identity & purpose',
    prompt: 'I feel worthless, confused about who I am, or uncertain why I am here.',
    description:
      'Belonging to God, vocation, dignity, transformation, and living from received identity.',
    companionId: 'snow',
    strongholdAction:
      'Replace the accusation with one identity statement grounded in the passage, then act from it once today.',
  },
  {
    id: 'gratitude',
    label: 'Gratitude & joy',
    prompt: 'I want to notice what is good, celebrate, or return thanks.',
    description: 'Remembering gifts, worship, joy, generosity, and carrying gratitude into action.',
    companionId: 'selah',
    strongholdAction:
      'Name three specific gifts, thank God for each one, and turn one of them into generosity toward someone else.',
  },
];

type PassageRow = readonly [
  reference: string,
  theme: string,
  context: string,
  observe: string,
  apply: string,
  prayer: string,
];

function makePassages(concern: SanctuaryConcern, rows: readonly PassageRow[]) {
  return rows.map(
    ([reference, theme, context, observe, apply, prayer], index): ScripturePassageDefinition => ({
      id: `${concern}:${index + 1}`,
      concern,
      reference,
      theme,
      context,
      observe,
      apply,
      prayer,
    }),
  );
}

export const SCRIPTURE_LIBRARY: ScripturePassageDefinition[] = [
  ...makePassages('sexual-integrity', [
    [
      '1 Corinthians 6:12–20',
      'Freedom with a purpose',
      'Paul challenges a church that confused permission with freedom and reminds them that the body belongs inside worship.',
      'Which appetite is trying to master you, and how does belonging to Christ change the decision in front of you?',
      'Move one recurring trigger out of easy reach before the day ends.',
      'Offer your body to God without disgust and ask for freedom that serves love.',
    ],
    [
      '1 Thessalonians 4:3–8',
      'Holiness and honorable desire',
      'Paul connects sexual holiness with learning self-control and refusing to treat another person as an object for appetite.',
      'What would it mean to approach your own body and other people with honor today?',
      'Write one boundary that protects dignity rather than merely avoiding punishment.',
      'Ask for desire to be trained toward holiness, patience, and genuine care.',
    ],
    [
      '2 Timothy 2:22–26',
      'Flee and pursue',
      'Paul does not tell Timothy only to resist youthful passions; he tells him what to run toward and whom to pursue it with.',
      'What healthy pursuit and what trustworthy people belong on the other side of fleeing?',
      'Choose the replacement action now: shared space, movement, a call, prayer, or focused work.',
      'Ask for a clean heart, wise escape, and companions who pursue what is good.',
    ],
    [
      'James 1:12–16',
      'The anatomy of temptation',
      'James distinguishes God’s character from the internal process by which desire grows, conceives, and becomes action.',
      'Where in the sequence can you interrupt the pattern before it gains momentum?',
      'Name the earliest recognizable signal and attach one immediate response to it.',
      'Ask for honesty about desire without blaming God, circumstance, or your worth.',
    ],
    [
      'Matthew 5:27–30',
      'Serious boundaries',
      'Jesus treats lust as a heart-level issue and uses forceful imagery to emphasize removing access to what repeatedly causes harm.',
      'What access are you protecting even though it repeatedly pulls you away from the person you want to become?',
      'Remove, block, relocate, or surrender one concrete access point.',
      'Ask for courage to choose costly freedom over familiar secrecy.',
    ],
    [
      'Psalm 119:9–16',
      'A mind stored with truth',
      'The psalmist connects a guarded path with seeking, remembering, speaking, and delighting in God’s words.',
      'Which practice in this passage is missing when temptation becomes loud?',
      'Read the selected verses aloud and carry one sentence into the next vulnerable hour.',
      'Ask for truth to become present and desirable when old images or habits return.',
    ],
    [
      'Romans 13:12–14',
      'Put on the new day',
      'Paul describes discipleship as waking, laying aside hidden works, and refusing to pre-plan opportunities for disordered desire.',
      'Where have you been quietly making provision for the very behavior you say you want to leave?',
      'Change tonight’s environment before temptation arrives rather than during it.',
      'Ask to walk openly, awake to choice, and clothed in Christlike character.',
    ],
    [
      'Galatians 5:16–25',
      'Desire redirected by the Spirit',
      'Paul contrasts the works that consume freedom with the fruit slowly formed by walking in step with the Spirit.',
      'Which fruit would directly answer the emotional need beneath today’s urge?',
      'Choose one fruit—peace, patience, self-control, love—and practice it toward a real person.',
      'Ask the Spirit to form more than restraint: a life with better desires and deeper connection.',
    ],
  ]),
  ...makePassages('shame', [
    [
      'Romans 8:1–4',
      'No condemnation',
      'Paul announces that those in Christ are not defined by a condemning verdict and describes a new power at work within weakness.',
      'What is the difference between conviction that leads home and condemnation that tells you to hide?',
      'Rewrite one condemning statement as an honest confession followed by a truthful next step.',
      'Thank God that grace can tell the truth without destroying the person returning.',
    ],
    [
      'Psalm 51:1–12',
      'Confession that asks for renewal',
      'David does not minimize his sin, yet he asks for cleansing, truth, restored joy, and a willing spirit rather than permanent exile.',
      'Which request in this prayer do you most need to make honestly?',
      'Pray the passage slowly, pausing where your own words need to enter.',
      'Ask for mercy, inner truth, restored joy, and willingness to begin again.',
    ],
    [
      '1 John 1:5–9',
      'Walking into the light',
      'John connects fellowship with honest confession and God’s faithful cleansing, rejecting both denial and despair.',
      'What becomes possible when confession is understood as movement toward light rather than exposure for humiliation?',
      'Tell the truth to God and, when appropriate, one trustworthy person.',
      'Ask for courage to leave secrecy and receive cleansing without bargaining.',
    ],
    [
      'Luke 15:11–24',
      'The Father who runs',
      'Jesus portrays a returning child rehearsing shame while the father moves first with compassion, restoration, and welcome.',
      'Which part of your rehearsed self-punishment is the father in this story refusing to endorse?',
      'Come back through one concrete practice instead of waiting to feel worthy first.',
      'Receive welcome, then ask for strength to live as someone restored rather than merely tolerated.',
    ],
    [
      'Hebrews 4:14–16',
      'Approach the throne',
      'Because Jesus understands human weakness, the response to need is confident approach for mercy and timely help.',
      'What makes you want to withdraw precisely when this passage tells you to approach?',
      'Pray before fixing your emotional state; bring the need while it is still messy.',
      'Ask boldly for mercy for what happened and help for what happens next.',
    ],
    [
      'Micah 7:8–9',
      'Fallen but not abandoned',
      'Micah speaks from consequences without treating darkness as the final location; God remains both judge and advocate.',
      'How can you accept responsibility without declaring the story finished?',
      'Identify one consequence to face and one hopeful action to take.',
      'Ask for light within consequence and patience while repair becomes visible.',
    ],
    [
      '2 Corinthians 7:8–11',
      'Grief that produces change',
      'Paul distinguishes grief that leads toward repentance and eagerness from grief that collapses into death and paralysis.',
      'Is your sorrow producing honest action, or only repeated self-attack?',
      'Turn regret into one measurable repair or protective boundary.',
      'Ask for sorrow that becomes courage, clarity, and changed direction.',
    ],
    [
      'Zechariah 3:1–5',
      'Accusation answered',
      'The prophet sees a stained priest accused, cleansed, reclothed, and restored to service by God’s command.',
      'Which accusation keeps speaking after confession, and whose verdict has greater authority?',
      'Picture leaving the stained garment behind and name the responsibility you are still allowed to carry.',
      'Ask to receive cleansing and return to faithful service without pretending the stain never existed.',
    ],
  ]),
  ...makePassages('anger', [
    [
      'James 1:19–21',
      'Slow enough to hear',
      'James connects quick listening, slow speech, and slow anger with receiving God’s word rather than producing our preferred version of justice.',
      'What have you not heard because anger prepared the response too early?',
      'Delay your next response and write what the other person might be experiencing.',
      'Ask for anger that submits to wisdom instead of controlling the room.',
    ],
    [
      'Ephesians 4:25–32',
      'Anger without a foothold',
      'Paul acknowledges anger while warning against sustained hostility, corrosive speech, and bitterness that makes room for further harm.',
      'Which part of the anger is becoming a home rather than a signal?',
      'Set a time to address the issue directly, calmly, and without contempt.',
      'Ask for truthful speech, clean boundaries, and tenderness that does not deny harm.',
    ],
    [
      'Proverbs 15:1–4',
      'The temperature of words',
      'Wisdom literature observes how tone can turn conflict, inflame it, or become healing for another person’s spirit.',
      'Which words would be true but unnecessarily scorching?',
      'Rewrite the message with the same boundary and half the heat.',
      'Ask for a guarded tongue that serves truth and repair.',
    ],
    [
      'Psalm 37:1–9',
      'Releasing the need to control outcomes',
      'The psalm addresses agitation over wrongdoing by pairing trust, patient action, and release of anger with confidence in God’s justice.',
      'What outcome are you trying to force because waiting feels like surrender?',
      'Choose the faithful action within your control and release the rest for today.',
      'Ask for justice without vengeance and patience without passivity.',
    ],
    [
      'Romans 12:17–21',
      'Overcoming evil differently',
      'Paul refuses revenge while making room for justice, practical care, and a form of goodness that does not imitate the harm received.',
      'How would retaliation make you resemble the thing that wounded you?',
      'Protect the boundary, refuse revenge, and do one good action that remains safe and wise.',
      'Ask to be freed from evil’s attempt to reproduce itself through your response.',
    ],
    [
      'Jonah 4:1–11',
      'Anger examined by compassion',
      'Jonah’s anger exposes how deeply he wanted mercy for himself and judgment for people he despised.',
      'Who do you believe is less deserving of patience than you are?',
      'Name the humanity of the person without excusing what they did.',
      'Ask for compassion large enough to coexist with truth and accountability.',
    ],
    [
      'Matthew 5:21–24',
      'Repair before performance',
      'Jesus connects contempt and unresolved relational rupture with worship, placing reconciliation and responsibility near the center of devotion.',
      'Is there an apology, conversation, or boundary you are avoiding behind religious activity?',
      'Plan one safe repair attempt, without forcing reconciliation where danger remains.',
      'Ask for humility to address your part and wisdom about what belongs to the other person.',
    ],
    [
      'Colossians 3:12–15',
      'Clothed for conflict',
      'Paul describes compassion, humility, patience, forgiveness, love, and peace as practices of a chosen community identity.',
      'Which quality must you put on before returning to this conflict?',
      'Choose one quality and define what it will look like in the next interaction.',
      'Ask to be dressed in character stronger than the emotion of the moment.',
    ],
  ]),
  ...makePassages('sadness', [
    [
      'Psalm 42',
      'Speaking hope inside heaviness',
      'The psalmist names tears, absence, memory, and inner turmoil while repeatedly speaking toward hope rather than denying sorrow.',
      'What does your soul need you to name before you tell it to hope?',
      'Write one lament sentence and one reason to remain for tomorrow.',
      'Ask God to meet both the thirst and the questions without requiring a cheerful performance.',
    ],
    [
      'Psalm 34:17–20',
      'Near to the brokenhearted',
      'The psalm does not promise an untroubled life; it emphasizes God’s nearness and rescue amid many afflictions.',
      'How would today change if brokenness were a location God approaches rather than avoids?',
      'Let one safe person know the day is heavy instead of carrying it invisibly.',
      'Ask for nearness you can receive through Scripture, rest, and trustworthy people.',
    ],
    [
      'Lamentations 3:19–26',
      'Hope remembered deliberately',
      'In the middle of communal devastation, the writer deliberately calls God’s mercy and faithfulness back into view.',
      'What true memory can sit beside the pain without erasing it?',
      'Record one mercy from the last twenty-four hours, however small.',
      'Ask for enough hope to wait through this day rather than solve the whole future.',
    ],
    [
      '2 Corinthians 1:3–7',
      'Comfort that can be shared',
      'Paul describes comfort received in affliction as something that can eventually become presence for someone else.',
      'What kind of comfort do you need—not advice, but actual comfort?',
      'Ask one person for a specific form of presence.',
      'Receive comfort without rushing to make the suffering useful.',
    ],
    [
      'John 11:32–36',
      'Jesus weeps',
      'Jesus meets grief with tears even while knowing resurrection is ahead, honoring sorrow rather than bypassing it with explanation.',
      'What sadness have you been judging because you think faith should make you unaffected?',
      'Give the grief ten honest minutes without correcting it.',
      'Ask Jesus to be present in the tears before asking for them to stop.',
    ],
    [
      '1 Kings 19:1–8',
      'Care before instruction',
      'Elijah collapses after fear and exhaustion; the first response he receives is sleep, food, water, and gentle continuation.',
      'Which physical need is intensifying the emotional darkness?',
      'Choose water, food, medication, sleep, sunlight, or safe company as a faithful next step.',
      'Ask for enough strength for the next stage, not the entire journey.',
    ],
    [
      'Psalm 13',
      'How long and still I trust',
      'David moves through protest, petition, trust, and praise without pretending the unanswered period was short.',
      'Which “how long” question needs permission to be spoken?',
      'Write your own four-part prayer: protest, request, trust, remembered goodness.',
      'Ask for room to lament and a thread of trust strong enough to hold it.',
    ],
    [
      'Romans 8:18–27',
      'Groaning with help',
      'Paul places creation, believers, and the Spirit within shared groaning, where weakness in prayer is met by divine intercession.',
      'What if wordless heaviness is not failed prayer?',
      'Sit quietly for two minutes and allow the need to exist before God without explanation.',
      'Ask the Spirit to carry what language cannot currently hold.',
    ],
  ]),
  ...makePassages('loneliness', [
    [
      'Psalm 27:7–14',
      'Seeking presence while waiting',
      'David longs for God’s face, fears abandonment, and practices courage inside an unresolved wait.',
      'Which absence feels loudest, and what kind of presence are you actually longing for?',
      'Name the need directly instead of disguising it as distraction.',
      'Ask to recognize God’s presence and to receive courage for human connection.',
    ],
    [
      'Psalm 68:5–6',
      'God places the lonely',
      'The psalm praises God as defender and household-maker, presenting belonging as a concern of divine justice and care.',
      'Where might belonging require letting yourself be known rather than merely being near people?',
      'Choose one community space to enter consistently instead of waiting for instant closeness.',
      'Ask for a household of safe, reciprocal relationships.',
    ],
    [
      'Hebrews 10:23–25',
      'Practicing presence with others',
      'The writer connects hope with gathering, mutual encouragement, and intentionally considering how to stir one another toward love.',
      'Who helps you remain honest and hopeful, and who might need your presence too?',
      'Schedule one real conversation or shared activity this week.',
      'Ask for courage to participate in community before loneliness says you are unwanted.',
    ],
    [
      'Genesis 2:18–25',
      'Created for relationship',
      'The creation story names isolation as not good and portrays mutuality, recognition, and unashamed presence as part of human design.',
      'How has a legitimate need for closeness been redirected into a substitute that cannot know you?',
      'Write what genuine intimacy would include beyond physical release.',
      'Ask for patient, honorable connection and freedom from counterfeit closeness.',
    ],
    [
      '1 Kings 19:9–18',
      'You are not the only one',
      'Elijah’s isolated perspective is met by God’s quiet presence, a new assignment, and the revelation that faithful others remain.',
      'What does loneliness currently claim that may not be the complete picture?',
      'Identify one person or community you have not yet allowed to help.',
      'Ask to hear the quiet truth beneath isolation’s absolute statements.',
    ],
    [
      'John 15:9–17',
      'Abiding and friendship',
      'Jesus connects remaining in love with obedience, joy, chosen friendship, and love that takes concrete action for others.',
      'How can receiving love become participation rather than passive longing?',
      'Offer one sincere act of friendship without using it to earn worth.',
      'Ask to remain in love and become capable of mutual, patient friendship.',
    ],
    [
      '2 Timothy 4:9–18',
      'Abandoned yet accompanied',
      'Paul names people who left, people he still needs, and the Lord who stood with him—spiritual presence without denial of human absence.',
      'Can you name both the abandonment and the people you still need without shame?',
      'Ask someone specifically for company, help, or time.',
      'Ask for God’s presence and the humility to seek human support too.',
    ],
    [
      'Ecclesiastes 4:9–12',
      'The strength of companionship',
      'The teacher describes practical benefits of shared work, help after falling, warmth, and resistance against threat.',
      'Where are you trying to live as though needing help were weakness?',
      'Choose one burden that should no longer be carried alone.',
      'Ask for trustworthy companionship and the courage to become trustworthy in return.',
    ],
  ]),
  ...makePassages('stress', [
    [
      'Matthew 6:25–34',
      'Today-sized trust',
      'Jesus redirects anxious attention from imagined futures toward the Father’s care and the responsibilities of the present day.',
      'Which future problem are you attempting to live before it arrives?',
      'Write today’s responsibility and postpone tomorrow’s problem until its proper time.',
      'Ask for daily bread, present attention, and trust that does not require total control.',
    ],
    [
      'Philippians 4:4–9',
      'Prayer and trained attention',
      'Paul pairs specific prayer and thanksgiving with deliberate attention to what is true, honorable, just, and worthy.',
      'What thought has been rehearsed without being tested for truth?',
      'Turn one worry into a specific request and one specific thank-you.',
      'Ask for guarded thoughts and peace that can coexist with unfinished circumstances.',
    ],
    [
      '1 Peter 5:6–10',
      'Casting care and staying watchful',
      'Peter connects humility, releasing anxiety, sober awareness, resistance, community suffering, and eventual restoration.',
      'Which burden are you carrying because surrender feels like irresponsibility?',
      'Name what belongs to your action and what must be cast beyond your control.',
      'Ask for alertness without panic and restoration after the pressure.',
    ],
    [
      'Psalm 46',
      'Stillness in upheaval',
      'The psalm describes instability on a massive scale while locating refuge in God’s presence and command to become still.',
      'What inner earthquake is currently defining the entire landscape?',
      'Pause all input for five minutes and breathe slowly through the passage.',
      'Ask to know refuge without needing the surroundings to become quiet first.',
    ],
    [
      'Proverbs 3:5–8',
      'Trust beyond your map',
      'Wisdom calls for wholehearted trust, acknowledged dependence, and humility about the limits of personal understanding.',
      'Where has planning crossed into the demand to guarantee every outcome?',
      'Take the next wise step and release the demand to see five steps farther.',
      'Ask for a straight path, humble judgment, and bodily peace.',
    ],
    [
      'Isaiah 26:3–4',
      'A stayed mind',
      'Isaiah connects peace with a mind repeatedly supported by trust rather than momentary absence of threat.',
      'What helps your mind return after it wanders toward catastrophe?',
      'Choose a short truth from the passage as today’s return point.',
      'Ask for attention that can be stayed and trust that can be practiced repeatedly.',
    ],
    [
      'Luke 10:38–42',
      'One necessary thing',
      'Martha’s legitimate service becomes anxious distraction while Mary receives permission to attend to what is necessary first.',
      'Which good responsibilities are crowding out the necessary center?',
      'Remove one nonessential task and give that time to presence.',
      'Ask for freedom from proving your worth through frantic usefulness.',
    ],
    [
      'Exodus 18:13–24',
      'Limits and shared load',
      'Moses’ exhausting leadership pattern is confronted as unsustainable, and wisdom arrives through delegation and structure.',
      'What are you doing alone that was never meant to depend entirely on you?',
      'Delegate, defer, or delete one responsibility.',
      'Ask for humility to accept limits and wisdom to build support.',
    ],
  ]),
  ...makePassages('numbness', [
    [
      'Ezekiel 36:25–27',
      'A renewed heart',
      'God promises cleansing, a responsive heart, and a Spirit-enabled way of living to people unable to renovate themselves.',
      'What are you trying to force through emotion that must first be received as renewal?',
      'Ask honestly for willingness before asking for intensity.',
      'Ask for a living heart and strength to take the next obedient step.',
    ],
    [
      'Psalm 143',
      'Remembering when the spirit fails',
      'David names a faint spirit, remembers God’s works, stretches out empty hands, and asks to be taught the way forward.',
      'Which remembered work of God can interrupt the claim that nothing is happening?',
      'Review one older journal entry, answered prayer, or season of help.',
      'Ask to hear steadfast love in the morning and to know the path for today.',
    ],
    [
      'Revelation 2:1–7',
      'Returning to first practices',
      'The church at Ephesus has endurance and discernment but has left its first love; the call is to remember, repent, and do earlier works.',
      'Which practice once helped love become active rather than theoretical?',
      'Resume one former practice at a sustainable size.',
      'Ask not merely to perform duty but to return through faithful action.',
    ],
    [
      'Isaiah 55:1–3',
      'Come while empty',
      'Isaiah invites thirsty people without resources to receive what satisfies instead of spending themselves on what cannot nourish.',
      'What substitute has consumed energy without feeding you?',
      'Replace one numbing routine with ten minutes of receiving Scripture, food, rest, or company.',
      'Ask for restored appetite for what gives life.',
    ],
    [
      'Mark 9:14–29',
      'Honest dependence',
      'The disciples confront a problem beyond their practiced confidence, and Jesus redirects them toward dependent prayer.',
      'Where has spiritual routine become self-reliance or quiet avoidance?',
      'Pray one unpolished request aloud instead of waiting for feeling.',
      'Ask for dependence that survives emotional flatness.',
    ],
    [
      'Psalm 63',
      'Seeking in a dry land',
      'David describes thirst and deliberate remembrance while physically displaced, showing desire practiced before conditions improve.',
      'What can you remember about God even if you cannot currently feel it?',
      'Name one remembered attribute and sit with it for three minutes.',
      'Ask for desire to awaken through remembrance and praise.',
    ],
    [
      'Romans 12:1–2',
      'Renewal through offered life',
      'Paul describes worship as embodied offering and transformation through a renewed mind rather than passive conformity.',
      'Which repeated environment is shaping you while you feel detached?',
      'Change one input and offer one ordinary task as worship.',
      'Ask for a renewed mind and discernment inside ordinary life.',
    ],
    [
      'Hosea 6:1–3',
      'Returning and pressing on',
      'The prophet calls people to return and continue knowing God with confidence in his life-giving arrival.',
      'What would returning look like before certainty or enthusiasm returns?',
      'Choose the next two days of a small practice rather than demanding a permanent emotional breakthrough.',
      'Ask for faithful return and patience with gradual renewal.',
    ],
  ]),
  ...makePassages('focus', [
    [
      'Luke 5:15–16',
      'Withdrawal on purpose',
      'As demands and attention increase, Jesus repeatedly withdraws to quiet places and prays.',
      'What must you step away from in order to be present rather than merely available?',
      'Schedule a recurring quiet place and protect it from notifications.',
      'Ask for the courage to withdraw without guilt and return with love.',
    ],
    [
      'Mark 1:35–39',
      'Prayer before demand',
      'Jesus seeks solitude before the day’s voices define his priorities, then returns with clarity about his mission.',
      'Which voice currently speaks first and loudest into your day?',
      'Place Scripture and prayer before one habitual source of input tomorrow.',
      'Ask for mission clarity before urgency begins assigning it for you.',
    ],
    [
      'Psalm 1',
      'Meditation and rootedness',
      'The psalm contrasts scattered influence with repeated meditation that forms a rooted, fruitful life over time.',
      'What counsel and media are currently planting themselves through repetition?',
      'Read one short passage morning and evening for three days.',
      'Ask to become rooted through patient attention rather than constant novelty.',
    ],
    [
      'Joshua 1:7–9',
      'Attention joined to action',
      'Joshua is told to keep the instruction near, meditate on it, and act carefully while stepping into intimidating responsibility.',
      'What truth do you know but repeatedly fail to carry into action?',
      'Write one action directly beneath the passage and complete it today.',
      'Ask for courage shaped by remembered instruction.',
    ],
    [
      'Colossians 3:1–4',
      'Setting the mind',
      'Paul treats attention as an intentional orientation grounded in a deeper identity and future with Christ.',
      'What has captured attention without deserving authority over it?',
      'Remove one distraction from the first and last fifteen minutes of the day.',
      'Ask for attention aligned with who you are becoming.',
    ],
    [
      'Hebrews 12:1–3',
      'Looking toward endurance',
      'The writer connects removing entanglement, running patiently, and fixing attention on Jesus when weariness grows.',
      'What weight is not necessarily evil but is making faithful focus harder?',
      'Lay aside one unnecessary weight for the next week.',
      'Ask for endurance strengthened by a clearer object of attention.',
    ],
    [
      'Psalm 119:33–40',
      'Teach, turn, and incline',
      'The psalmist repeatedly asks God to teach understanding, turn the eyes, and incline the heart, treating focus as grace-assisted practice.',
      'Where do your eyes go automatically when quiet begins?',
      'Use the passage as a written prayer before the next study session.',
      'Ask for turned eyes, an inclined heart, and life in what is good.',
    ],
    [
      'Daniel 6:10–13',
      'A practiced rhythm',
      'Daniel’s prayer is not an emergency invention; it is a known rhythm that remains when pressure changes around him.',
      'What rhythm would make prayer less dependent on mood or crisis?',
      'Choose a repeatable place and time for one week.',
      'Ask for quiet consistency stronger than interruption.',
    ],
  ]),
  ...makePassages('doubt', [
    [
      'Mark 9:20–24',
      'Belief that brings unbelief along',
      'A desperate father speaks faith and doubt in the same sentence, and Jesus receives the honesty rather than demanding polished certainty.',
      'What do you believe and struggle to believe at the same time?',
      'Write both halves without forcing either one to disappear.',
      'Ask directly for help with unbelief.',
    ],
    [
      'John 20:24–29',
      'Questions met with presence',
      'Thomas’ absence and demand for evidence are met by Jesus’ return, invitation, and call toward trust.',
      'What evidence or experience are you longing for, and what has already been given?',
      'Review one reason you began believing and one present question.',
      'Ask for patient encounter rather than shame about the question.',
    ],
    [
      'Psalm 73',
      'Perspective restored in worship',
      'The psalmist’s envy and confusion are spoken openly until entering God’s presence changes the scale of what he sees.',
      'Which comparison has made faithfulness look foolish?',
      'Step away from comparison and name what remains truly good.',
      'Ask for perspective that can hold injustice without abandoning God.',
    ],
    [
      'Habakkuk 3:17–19',
      'Trust without visible yield',
      'Habakkuk imagines devastating loss and still chooses rejoicing rooted in God rather than favorable output.',
      'What outcome has become the condition you placed on trust?',
      'Name what would remain worthy even if the desired result is delayed.',
      'Ask for strength to walk without pretending the empty field is full.',
    ],
    [
      'Jude 20–23',
      'Mercy toward doubt',
      'Jude instructs a community to remain in God’s love and show mercy to those who doubt rather than treating questions as contamination.',
      'How would you speak to your doubt if mercy rather than panic led the conversation?',
      'Share one question with a mature, trustworthy believer.',
      'Ask for mercy, patience, and community while understanding grows.',
    ],
    [
      'Romans 8:31–39',
      'Love stronger than separation',
      'Paul surveys accusation, suffering, danger, and spiritual powers before insisting that none can sever God’s love in Christ.',
      'Which circumstance are you interpreting as proof of abandonment?',
      'List the circumstance separately from the conclusion you attached to it.',
      'Ask to know enduring love without requiring painless evidence.',
    ],
    [
      'Luke 24:13–35',
      'Companionship on the confused road',
      'Jesus walks with disappointed disciples, listens to their failed expectations, reframes Scripture, and becomes recognized over time.',
      'Which expectation failed so badly that it changed how you interpret God?',
      'Tell the story of disappointment honestly, then look for what you may not yet recognize.',
      'Ask for companionship, understanding, and eyes opened gradually.',
    ],
    [
      'Psalm 77',
      'Remembering through unanswered questions',
      'The psalmist voices sleepless questions, then deliberately remembers God’s past action without receiving a simple explanation.',
      'What can be remembered when an answer cannot yet be reached?',
      'Create a short record of past faithfulness to revisit during future doubt.',
      'Ask for memory strong enough to accompany unresolved questions.',
    ],
  ]),
  ...makePassages('forgiveness', [
    [
      'Matthew 18:21–35',
      'Received mercy and released debt',
      'Jesus tells a severe story about someone who receives enormous mercy but refuses to let mercy reshape his treatment of another.',
      'What debt are you repeatedly collecting in imagination?',
      'Release revenge while naming any boundary or justice process that still belongs.',
      'Ask to remember received mercy without minimizing the harm.',
    ],
    [
      'Colossians 3:12–14',
      'Forgiveness within chosen character',
      'Paul places forgiveness among compassion, humility, patience, and love—qualities practiced from a received identity.',
      'Which quality is needed before you can address this injury wisely?',
      'Choose one non-retaliatory action that does not violate safety.',
      'Ask for love that binds together truth, patience, and boundaries.',
    ],
    [
      'Ephesians 4:31–5:2',
      'Putting away corrosive patterns',
      'Paul calls for the removal of bitterness and malice while imitating costly love, not pretending injury never occurred.',
      'Which repeated thought or behavior is allowing the wound to keep shaping you?',
      'Interrupt one ritual of resentment, such as rehearsing the argument or checking the person’s life.',
      'Ask to release what corrodes without surrendering discernment.',
    ],
    [
      'Genesis 50:15–21',
      'Refusing the place of God',
      'Joseph acknowledges intended evil and his power over those who harmed him, yet refuses revenge and sees a larger redemptive story.',
      'Can you call the harm evil without making revenge your responsibility?',
      'Name the truth, the boundary, and the future you want free from the offender’s control.',
      'Ask for freedom from vengeance and wisdom about any possible relationship.',
    ],
    [
      'Luke 23:32–34',
      'Mercy in the presence of harm',
      'Jesus prays for forgiveness amid active injustice; the prayer does not declare the violence acceptable or unreal.',
      'What would mercy mean if it did not require calling harm good?',
      'Pray willingness to release revenge even if emotion has not caught up.',
      'Ask for mercy that protects your soul while justice remains truthful.',
    ],
    [
      'Romans 12:14–21',
      'Leaving room for justice',
      'Paul forbids personal revenge, commands honest empathy and peace where possible, and leaves judgment outside personal retaliation.',
      'What belongs to peace, what belongs to boundaries, and what belongs to God or proper authorities?',
      'Write those three categories separately before choosing the next step.',
      'Ask for peace where possible and courage where protection is necessary.',
    ],
    [
      'Psalm 32',
      'The freedom of acknowledged wrong',
      'David describes the physical weight of concealed guilt and the relief of confession, forgiveness, instruction, and restored joy.',
      'Is the forgiveness needed from you, for you, or both?',
      'Confess your own part specifically without taking responsibility for someone else’s choices.',
      'Ask for honest release and teachability after forgiveness.',
    ],
    [
      'Matthew 6:9–15',
      'Forgiveness inside daily prayer',
      'Jesus places receiving and extending forgiveness within a prayer for daily bread, protection, God’s reign, and deliverance.',
      'Why might forgiveness need to be prayed repeatedly rather than felt once?',
      'Add the person or injury to a brief daily prayer without forcing contact.',
      'Ask for daily release, wise protection, and freedom from bitterness.',
    ],
  ]),
  ...makePassages('identity', [
    [
      'Ephesians 1:3–14',
      'Identity received in Christ',
      'Paul begins with a cascade of belonging, adoption, grace, redemption, purpose, and promised inheritance before giving behavioral instruction.',
      'Which received identity is hardest for you to believe without earning it?',
      'Begin today’s self-description with what is received rather than what was achieved.',
      'Thank God for belonging that precedes performance.',
    ],
    [
      '1 Peter 2:9–12',
      'Called and sent',
      'Peter gives a scattered community a shared identity tied to mercy, witness, and honorable life among others.',
      'How does being called out of darkness shape what you are called into?',
      'Choose one action that makes mercy visible to another person.',
      'Ask to live as someone who belongs and has something good to declare.',
    ],
    [
      'Psalm 139:1–18',
      'Fully known',
      'The psalm explores God’s knowledge, presence, creation, and attention at a depth that makes hiding impossible and belonging intimate.',
      'Which part of being fully known feels comforting, and which part feels threatening?',
      'Sit with one line that makes concealment unnecessary.',
      'Ask to receive being known without performing or disappearing.',
    ],
    [
      '2 Corinthians 5:14–21',
      'New creation and reconciliation',
      'Paul describes identity reshaped by Christ’s love, a new way of seeing people, and participation in reconciliation.',
      'Which old label is trying to overrule the new direction of your life?',
      'Act once as an ambassador of reconciliation without forcing an unsafe relationship.',
      'Ask to see yourself and others through redemption rather than consumption or contempt.',
    ],
    [
      'Romans 8:14–17',
      'Adopted, not enslaved to fear',
      'Paul contrasts slavery to fear with the Spirit of adoption and the intimate cry of a child who belongs.',
      'Where are you still relating to God mainly as a terrified employee?',
      'Pray using the language of a child asking a trustworthy Father for help.',
      'Ask to live from adoption rather than fear of rejection.',
    ],
    [
      'Colossians 3:1–17',
      'Putting on the renewed self',
      'Paul joins hidden identity with practical removal and adoption of habits, relationships, words, and gratitude.',
      'What must be put off, and what specific quality must replace it?',
      'Define the replacement behavior, not only the prohibited behavior.',
      'Ask for a renewed self visible in ordinary choices.',
    ],
    [
      'Galatians 2:19–20',
      'A life re-centered',
      'Paul describes an identity no longer organized around self-justification but around Christ’s life and self-giving love.',
      'What are you trying to prove that has already been answered by love?',
      'Release one performance designed only to earn worth.',
      'Ask to live by trust in love rather than constant self-verification.',
    ],
    [
      'Jeremiah 1:4–10',
      'Known before confidence',
      'Jeremiah’s calling is met by insecurity, but God’s knowledge, presence, and provision are not dependent on Jeremiah feeling impressive.',
      'Which limitation have you mistaken for disqualification?',
      'Take one small action aligned with calling while still feeling inadequate.',
      'Ask for courage grounded in presence rather than personality.',
    ],
  ]),
  ...makePassages('gratitude', [
    [
      'Psalm 103',
      'Remembering benefits',
      'The psalmist instructs his own soul not to forget mercy, healing, redemption, compassion, justice, and enduring love.',
      'Which gift has become invisible through familiarity?',
      'List five specific benefits and linger over one.',
      'Bless God with attention rather than rushing toward the next need.',
    ],
    [
      '1 Thessalonians 5:16–24',
      'Gratitude within a whole life',
      'Paul places rejoicing and thanksgiving beside prayer, discernment, testing, holiness, and trust in God’s faithfulness.',
      'How can gratitude remain honest without calling everything good?',
      'Thank God in the circumstance for one real gift, not for the harm itself.',
      'Ask for joy, discernment, and faithful formation together.',
    ],
    [
      'Philippians 1:3–11',
      'Thankfulness for people',
      'Paul’s gratitude becomes intercession for the continued growth, love, wisdom, and fruitfulness of people he values.',
      'Who has quietly strengthened your life without hearing it recently?',
      'Send a specific message of thanks that names what their presence changed.',
      'Thank God for them and pray for their growth, not only your benefit.',
    ],
    [
      'Luke 17:11–19',
      'Returning to give thanks',
      'Ten receive healing, but one interrupts forward movement to return, recognize the giver, and express gratitude.',
      'What answered need did you immediately replace with the next request?',
      'Return to one answered prayer and mark it deliberately.',
      'Give thanks before asking for anything new.',
    ],
    [
      'Colossians 3:15–17',
      'Gratitude shaping community',
      'Paul repeats thankfulness while describing peace, shared wisdom, worship, and ordinary action done in Christ’s name.',
      'How could gratitude change the atmosphere you bring into relationships today?',
      'Speak one appreciative truth in the next room you enter.',
      'Ask for thankfulness that becomes peace, wisdom, and service.',
    ],
    [
      'James 1:16–18',
      'Recognizing the source of good gifts',
      'James warns against deception and points toward God’s consistent generosity and creative purpose.',
      'Which good gift have you treated as entitlement, accident, or solely personal achievement?',
      'Name the gift, its source, and the responsibility it creates.',
      'Thank God and ask to steward the gift rather than merely consume it.',
    ],
    [
      'Psalm 136',
      'Repetition that remembers',
      'The psalm rehearses creation, rescue, provision, and history through a repeated declaration of enduring love.',
      'Which chapter of your history needs to be retold through the lens of enduring mercy?',
      'Write a short timeline with “steadfast love was present” beside each turning point.',
      'Thank God for love that remained through changing circumstances.',
    ],
    [
      'Ephesians 5:15–20',
      'Wise and thankful time',
      'Paul links careful living, redeemed time, spiritual fullness, worship, and thanksgiving in a difficult age.',
      'Where could gratitude help you use time more deliberately?',
      'Turn fifteen minutes of passive consumption into worship, service, or meaningful connection.',
      'Ask to live awake, wise, and thankful with the time available.',
    ],
  ]),
];

export const SNOW_SANCTUARY_LINES = [
  'You did not need the right words before entering. You only needed to stop hiding from what is here.',
  'We are not measuring how spiritual you feel. We are making room for truth, attention, and one honest return.',
  'Nothing you selected made me step farther away. Let us understand the need before demanding that you overpower it.',
  'The goal is not to perform a perfect quiet time. The goal is to remain present long enough to be known.',
  'You can come back more than once today. The reward records once; the door stays open.',
  'We will not turn pain into a character verdict. We will listen, read, pray, and choose the next faithful action.',
];

export const SELAH_SANCTUARY_LINES = [
  'Read slowly enough to notice what the passage actually says before asking it to solve everything.',
  'Prayer can begin with adoration, move through honesty, receive mercy, ask clearly, and surrender what remains.',
  'Conviction leads us toward God and changed action. Condemnation only tells us to hide. We will follow the voice that leads home.',
  'You are allowed to bring an unfinished emotion into Scripture. Reverence does not require pretending.',
  'Do not rush to the application before receiving the truth. Roots come before visible fruit.',
  'A brief honest prayer can become deep when you stay with each sentence instead of escaping into the next one.',
];

export const SPECIALIST_SANCTUARY_LINES: Record<SanctuaryConcern, string[]> = {
  'sexual-integrity': [
    'Amara: The urge may be sexual, but the need underneath it may be closeness, relief, reassurance, or escape. We can honor the need without feeding the pattern.',
    'Amara: Explicit content offers the appearance of intimacy without the risk of being known. You deserve connection that can actually recognize you.',
    'Amara: We are not declaring your sexuality filthy. We are teaching desire to live with dignity, patience, truth, and mutual humanity.',
  ],
  shame: [
    'Snow: Name what happened accurately, then stop turning an action into your entire identity. Repair needs honesty, not self-destruction.',
    'Snow: You do not have to injure yourself emotionally to prove that you understand the seriousness of the mistake.',
    'Snow: Recovery begins where concealment ends. We can tell the truth and still treat the returning person with care.',
  ],
  anger: [
    'Ember: The anger has information, but it does not get command authority. We slow the body before choosing the target.',
    'Ember: I will not ask you to call injustice acceptable. I will ask you not to let it recruit your mouth and hands.',
    'Ember: Delay the reaction. Keep the boundary. Refuse the cheap satisfaction of becoming cruel.',
  ],
  sadness: [
    'Snow: We are not making sadness audition for permission. Let the passage meet the weight that is actually here.',
    'Snow: If the day is heavy, the next faithful action may be water, food, medication, sunlight, rest, or telling someone.',
    'Snow: Spiritual care and professional care are allowed in the same life. Needing both is not a failure of faith.',
  ],
  loneliness: [
    'Amara: Loneliness can make counterfeit closeness look convincing. Let us answer the need for connection instead of insulting you for having it.',
    'Amara: Wanting to be held, chosen, heard, or desired is not shameful. The question is whether the chosen substitute can truly know you.',
    'Amara: We can practice direct, honorable connection—one message, one shared space, one honest sentence at a time.',
  ],
  stress: [
    'Snow: Not everything urgent belongs to this hour. Let us separate responsibility from imagined control.',
    'Snow: Your body may need evidence that the emergency has paused. Breathe, unclench, and choose only the next task.',
    'Snow: Rest is not a reward for finally becoming limitless. Limits are part of how you were made.',
  ],
  numbness: [
    'Snow: You do not have to manufacture feeling before returning. Presence can come first; emotion may follow later.',
    'Snow: Numbness is not proof that nothing matters. Sometimes it is evidence that too much has mattered for too long.',
    'Snow: Give me one honest sentence and five present minutes. We can begin there without pretending it is everything.',
  ],
  focus: [
    'Cipher: Attention is an environment problem as often as a motivation problem. Remove the competing signal before judging your devotion.',
    'Cipher: We do not need impressive concentration. We need a repeatable return point every time the mind wanders.',
    'Cipher: One passage, one timer, one face-down phone. Complexity is currently working for the distraction.',
  ],
  doubt: [
    'Selah: A question brought honestly into God’s presence is not the same as a conclusion made in isolation.',
    'Selah: Faith does not become stronger by lying about uncertainty. Bring the exact question and remain open to patient understanding.',
    'Selah: We can remember what is known while refusing to fake an answer for what is not.',
  ],
  forgiveness: [
    'Amara: Forgiveness can release revenge without restoring unsafe access. Mercy and boundaries are not enemies.',
    'Amara: Reconciliation requires truth, safety, and participation from more than one person. You are not responsible for manufacturing all three alone.',
    'Amara: We are freeing your future from the wound’s command, not editing the past into something harmless.',
  ],
  identity: [
    'Snow: The accusation is loud because it has been rehearsed. We will rehearse a truer name through action, not empty flattery.',
    'Snow: Your record contains choices and consequences. It does not contain permission to reduce an entire person to their worst hour.',
    'Snow: Purpose is often recognized through the next faithful responsibility before it is felt as a grand calling.',
  ],
  gratitude: [
    'Selah: Gratitude is attention made reverent. We slow down long enough for a gift to become visible again.',
    'Selah: Giving thanks does not deny pain. It refuses to let pain become the only true thing in the room.',
    'Selah: Let one received gift become generosity. Gratitude becomes strong when it travels through you.',
  ],
};

export const LONELINESS_INTEGRITY_LINES = [
  'Amara: This may not be only a fight against sexual appetite. It may be an attempt to escape the ache of not feeling chosen, touched, known, or accompanied.',
  'Amara: Explicit content can imitate access while protecting you from the vulnerability of real connection. The relief is immediate; the loneliness often returns heavier.',
  'Amara: We will interrupt the behavior and also care for the lonely person underneath it. Both parts deserve an honest response.',
  'Amara: Your need for intimacy is human. The pattern becomes harmful when it turns people into images and leaves you more hidden than before.',
  'Amara: Tonight’s victory may include leaving the trigger and reaching toward safe connection instead of demanding that willpower do every job.',
  'Amara: We are building a life where desire can move toward mutual love, patience, dignity, and being genuinely known.',
];

export function getSanctuaryConcern(id: SanctuaryConcern) {
  return SANCTUARY_CONCERNS.find((concern) => concern.id === id)!;
}

export function getScripturePassage(id: string) {
  return SCRIPTURE_LIBRARY.find((passage) => passage.id === id)!;
}
