import type { TitleDefinition } from '@/types/game';

export const TITLE_LIBRARY: TitleDefinition[] = [
  {
    id: 'newly-awakened',
    name: 'Newly Awakened',
    description: 'The system answered your initialization.',
    condition: 'Create a profile.',
    rarity: 'common',
    accent: '#43e6c2',
  },
  {
    id: 'first-step',
    name: 'First Step',
    description: 'One action changed the trajectory.',
    condition: 'Complete your first mission.',
    rarity: 'common',
    accent: '#9fb2bd',
  },
  {
    id: 'steady-hand',
    name: 'Steady Hand',
    description: 'Progress without spectacle.',
    condition: 'Complete 25 missions.',
    rarity: 'uncommon',
    accent: '#66d8c2',
  },
  {
    id: 'faithful-initiate',
    name: 'Faithful Initiate',
    description: 'A foundation built in quiet practice.',
    condition: 'Complete Faith Foundation.',
    rarity: 'rare',
    accent: '#b8a6ff',
  },
  {
    id: 'iron-routine',
    name: 'Iron Routine',
    description: 'The plan held after motivation faded.',
    condition: 'Complete 100 workouts.',
    rarity: 'epic',
    accent: '#94a3b8',
  },
  {
    id: 'quiet-resolve',
    name: 'Quiet Resolve',
    description: 'Discipline made visible through repetition.',
    condition: 'Complete Discipline Protocol.',
    rarity: 'rare',
    accent: '#8b5cf6',
  },
  {
    id: 'creator-in-motion',
    name: 'Creator in Motion',
    description: 'Ideas became actions.',
    condition: 'Complete 10 creator missions.',
    rarity: 'uncommon',
    accent: '#a78bfa',
  },
  {
    id: 'unbroken-focus',
    name: 'Unbroken Focus',
    description: 'Attention held its line.',
    condition: 'Reach Focus level 20.',
    rarity: 'rare',
    accent: '#8b5cf6',
  },
  {
    id: 'returning-hunter',
    name: 'Returning Hunter',
    description: 'You returned before the lapse became a life.',
    condition: 'Complete a recovery challenge.',
    rarity: 'uncommon',
    accent: '#43e6c2',
  },
  {
    id: 'keeper-of-momentum',
    name: 'Keeper of Momentum',
    description: 'You learned how to protect a pattern.',
    condition: 'Achieve 10 Perfect Days in one month.',
    rarity: 'epic',
    accent: '#a78bfa',
  },
  {
    id: 'disciplined-soul',
    name: 'Disciplined Soul',
    description: 'Commitment became character.',
    condition: 'Reach Discipline level 30.',
    rarity: 'epic',
    accent: '#8b5cf6',
  },
  {
    id: 'forged-repetition',
    name: 'Forged Through Repetition',
    description: 'A thousand ordinary actions became extraordinary.',
    condition: 'Complete 1,000 missions.',
    rarity: 'legendary',
    accent: '#c4b5fd',
  },
  {
    id: 'architect-of-worlds',
    name: 'Architect of Worlds',
    description: 'You kept building when no one was watching.',
    condition: 'Complete Creator’s Forge.',
    rarity: 'rare',
    accent: '#a78bfa',
  },
  {
    id: 'the-consistent',
    name: 'The Consistent',
    description: 'Your pattern became undeniable.',
    condition: 'Complete five Perfect Days in one week.',
    rarity: 'epic',
    accent: '#43e6c2',
  },
  {
    id: 'rank-breaker',
    name: 'Class Breaker',
    description: 'A former classification could no longer contain you.',
    condition: 'Advance class.',
    rarity: 'epic',
    accent: '#a78bfa',
  },
  {
    id: 'trial-conqueror',
    name: 'Trial Conqueror',
    description: 'Qualification became proof.',
    condition: 'Complete three Class Trials.',
    rarity: 'legendary',
    accent: '#c4b5fd',
  },
  {
    id: 'world-class-candidate',
    name: 'World-Class Candidate',
    description: 'The final classification has begun to take notice.',
    condition: 'Qualify for the World Class Trial.',
    rarity: 'ascendant',
    accent: '#f4f7fa',
  },
  {
    id: 'awakened-in-motion',
    name: 'Awakened in Motion',
    description: 'A complete week proved the system was real.',
    condition: 'Complete Seven-Day Awakening.',
    rarity: 'uncommon',
    accent: '#43e6c2',
  },
  {
    id: 'tempered-vessel',
    name: 'Tempered Vessel',
    description: 'Movement and strength answered together.',
    condition: 'Complete Body Tempering.',
    rarity: 'rare',
    accent: '#f0b35a',
  },
  {
    id: 'thirty-day-ascendant',
    name: 'Thirty-Day Ascendant',
    description: 'One month carried a new standard.',
    condition: 'Complete Thirty-Day Ascension.',
    rarity: 'legendary',
    accent: '#a78bfa',
  },
  {
    id: 'balanced-ascendant',
    name: 'Balanced Ascendant',
    description: 'No single strength concealed a neglected foundation.',
    condition: 'Complete Fivefold Balance.',
    rarity: 'legendary',
    accent: '#a78bfa',
  },
  {
    id: 'first-light',
    name: 'First Light',
    description: 'A perfect day was sealed.',
    condition: 'Earn your first Perfect Day.',
    rarity: 'uncommon',
    accent: '#43e6c2',
  },
  {
    id: 'sevenfold',
    name: 'Sevenfold',
    description: 'Seven complete days formed a chain.',
    condition: 'Reach a 7-day Perfect streak.',
    rarity: 'rare',
    accent: '#43e6c2',
  },
  {
    id: 'month-unbroken',
    name: 'Month Unbroken',
    description: 'The calendar bears your pattern.',
    condition: 'Reach a 30-day mission streak.',
    rarity: 'epic',
    accent: '#a78bfa',
  },
  {
    id: 'century-mark',
    name: 'Century Mark',
    description: 'One hundred completed days.',
    condition: 'Complete 100 days.',
    rarity: 'epic',
    accent: '#9fb2bd',
  },
  {
    id: 'long-campaign',
    name: 'Veteran of the Long Campaign',
    description: 'One year of recorded advancement.',
    condition: 'Complete 365 days.',
    rarity: 'legendary',
    accent: '#c4b5fd',
  },
  {
    id: 'gentle-strength',
    name: 'Gentle Strength',
    description: 'Power that still makes room for care.',
    condition: 'Reach Strength and Empathy level 15.',
    rarity: 'rare',
    accent: '#66d8c2',
  },
  {
    id: 'living-wisdom',
    name: 'Living Wisdom',
    description: 'Study changed the way you moved.',
    condition: 'Reach Wisdom level 25.',
    rarity: 'epic',
    accent: '#a78bfa',
  },
  {
    id: 'vital-current',
    name: 'Vital Current',
    description: 'Movement became a sustaining force.',
    condition: 'Reach Vitality level 20.',
    rarity: 'rare',
    accent: '#43e6c2',
  },
  {
    id: 'enduring-one',
    name: 'The Enduring One',
    description: 'Distance yielded to patience.',
    condition: 'Reach Endurance level 30.',
    rarity: 'epic',
    accent: '#f0b35a',
  },
  {
    id: 'signal-bearer',
    name: 'Signal Bearer',
    description: 'Kindness traveled farther because you sent it.',
    condition: 'Complete 100 kind messages.',
    rarity: 'epic',
    accent: '#43e6c2',
  },
  {
    id: 'deep-root',
    name: 'Deep Root',
    description: 'Faith grew beneath the visible surface.',
    condition: 'Reach Faith level 30.',
    rarity: 'epic',
    accent: '#a78bfa',
  },
  {
    id: 'focus-engine',
    name: 'Focus Engine',
    description: 'Attention became renewable.',
    condition: 'Complete 100 creator missions.',
    rarity: 'epic',
    accent: '#8b5cf6',
  },
  {
    id: 'record-keeper',
    name: 'Record Keeper',
    description: 'You carried your history without being ruled by it.',
    condition: 'Finalize 50 Daily Reviews.',
    rarity: 'rare',
    accent: '#9fb2bd',
  },
  {
    id: 'exception-wisely-used',
    name: 'Wisdom in Exception',
    description: 'Rest was chosen without abandoning the path.',
    condition: 'Use a protected exception.',
    rarity: 'uncommon',
    accent: '#66d8c2',
  },
  {
    id: 'recalibrated',
    name: 'Recalibrated',
    description: 'Recovery preserved the campaign.',
    condition: 'Complete a Recovery Mode period.',
    rarity: 'uncommon',
    accent: '#43e6c2',
  },
  {
    id: 'e-ranked',
    name: 'E-Class',
    description: 'The first classification beyond awakening.',
    condition: 'Reach E-Class.',
    rarity: 'rare',
    accent: '#8b5cf6',
  },
  {
    id: 'c-ranked',
    name: 'C-Class',
    description: 'Your record now reflects a serious campaign.',
    condition: 'Reach C-Class.',
    rarity: 'epic',
    accent: '#a78bfa',
  },
  {
    id: 's-ranked',
    name: 'S-Class',
    description: 'A classification reserved for the extraordinary.',
    condition: 'Reach S-Class.',
    rarity: 'legendary',
    accent: '#c4b5fd',
  },
  {
    id: 'beyond-measure',
    name: 'Beyond Measure',
    description: 'World Class was no longer a projection.',
    condition: 'Reach World Class.',
    rarity: 'ascendant',
    accent: '#f4f7fa',
  },
  {
    id: 'ten-levels',
    name: 'Threshold Walker',
    description: 'Ten account levels crossed.',
    condition: 'Reach account level 10.',
    rarity: 'uncommon',
    accent: '#43e6c2',
  },
  {
    id: 'fifty-levels',
    name: 'High-Level Candidate',
    description: 'A long campaign made visible.',
    condition: 'Reach account level 50.',
    rarity: 'legendary',
    accent: '#a78bfa',
  },
  {
    id: 'snows-constant',
    name: "Snow's Constant",
    description: 'You learned that being supported and staying true can exist in the same journey.',
    condition: 'Complete The One Who Stayed.',
    rarity: 'legendary',
    accent: '#86cfff',
  },
  {
    id: 'tempered-foundation',
    name: 'Tempered Foundation',
    description: 'Strength became a home you can keep returning to.',
    condition: 'Complete Tempered Foundation.',
    rarity: 'legendary',
    accent: '#f2a65a',
  },
  {
    id: 'rooted-light',
    name: 'Rooted in Light',
    description: 'Faith became a rhythm deeper than circumstance.',
    condition: 'Complete Rooted in Light.',
    rarity: 'legendary',
    accent: '#f4c95d',
  },
  {
    id: 'signal-made-real',
    name: 'Signal Made Real',
    description: 'An idea crossed the distance between intention and reality.',
    condition: 'Complete Signal to Reality.',
    rarity: 'legendary',
    accent: '#9b7bff',
  },
  {
    id: 'guardian-of-the-whole',
    name: 'Guardian of the Whole',
    description: 'Progress learned to protect the person making it.',
    condition: 'Complete Shelter Without Stagnation.',
    rarity: 'legendary',
    accent: '#55cbb7',
  },
  {
    id: 'reignited',
    name: 'Reignited',
    description: 'You learned how to begin again without burning yourself down.',
    condition: 'Complete Reignite Protocol.',
    rarity: 'legendary',
    accent: '#ff693f',
  },
  {
    id: 'heartwoven',
    name: 'Heartwoven',
    description: 'Connection grew brave, reciprocal, and honest.',
    condition: 'Complete The Courage to Connect.',
    rarity: 'legendary',
    accent: '#ff79b8',
  },
  {
    id: 'keeper-of-margin',
    name: 'Keeper of Margin',
    description:
      'Your resources gained direction, your future gained protection, and recovery replaced shame.',
    condition: "Complete The Keeper's Ledger.",
    rarity: 'legendary',
    accent: '#f4c95d',
  },
  {
    id: 'keeper-of-the-hearth',
    name: 'Keeper of the Hearth',
    description: 'Preparation became nourishment, savings, and a form of care you can repeat.',
    condition: 'Complete The Fire We Feed.',
    rarity: 'legendary',
    accent: '#ff8a3d',
  },
];

export function getTitle(id: string) {
  return TITLE_LIBRARY.find((title) => title.id === id);
}
